### ISSUE TITLE
upgrade tokio to 0.2 via new reqwests

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#101]
We are currently unable to upgrade tokio due to a non-existing reqwest release using tokio 0.2. But it's about to become available. Tracking issue.

**Comment by clux** [comment]
https://github.com/seanmonstar/reqwest/issues/721 is merged so master runs off that, and examples work with it, but awaiting a release of reqwest before we can publish `0.23.0`.

**Comment by SpyMachine** [comment]
Any chance of an alpha release that uses the master branch of reqwest? This is currently blocking me because of dependency issues.

**Comment by clux** [comment]
Not able to release to crates when using git dependencies unfortunately.

**Comment by SpyMachine** [comment]
reqwest 0.10.0 was just released :)

**Comment by clux** [comment]
Awesome. kube 0.23.0 released as well!
