### ISSUE TITLE
Need to check `k8s-openapi` features when importing

### ISSUE THREAD

**Issue by asthasr** [clux/kube-rs#106]
I am using EKS, which currently [supports only Kubernetes 1.14](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html). As such, I need to enable the `v1_14` feature when using `k8s-openapi`. Unfortunately, `kube` imports a resource which doesn't exist in this version:

```
use k8s_openapi::api::admissionregistration::v1beta1::ValidatingWebhook;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ValidatingWebhook`
 in `api::admissionregistration::v1beta1`
```

**Comment by clux** [comment]
Ugh, yeah, you're right. For now; I'd recommend you use 1.15 against a 1.14 cluster (whichi is almost certainly going to be fine), but we should check this properly. Thanks.
