### ISSUE TITLE
not working on linux with self-signed ca

### ISSUE THREAD

**Issue by mumutu66** [clux/kube-rs#110]
after installed  `vcpkg` ,  everything is good on windows  ,when turn to linux  get following error

```

TRACE kube::client] GET https://x.x.x.x:6443/apis/apps/v1/deployments?&limit=1
Error: ReqwestError: error sending request for url (https://x.x.x.x:6443/apis/apps/v1/deployments?&limit=1): error trying to connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264: (unable to get issuer certificate)


```

both with `incluster_config` or mount the kubeconfig in `/root/.kube/config`....so is there any workarounds ..

**Comment by clux** [comment]
Hm, I'm not sure what the correct way to do this is. You can check #89 for some ideas and background. The `insecure-skip-tls-verify` can be set in your kube config during testing IIRC. Never seen it fail in an actual cluster with an `incluster_config` though. You building your own cluster?

**Comment by mumutu66** [comment]
@clux thanks it works！  yes I am building my own cluster in production 。。and works well with client-go。。maybe the reqwest is too strict with tls。 
  [Access in cluster](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/)  says 
```
Since cluster certificates are typically self-signed, it may take special configuration to get your http client to use root certificate.

```
