### ISSUE TITLE
Gracefully handle out-of-order watch events

### ISSUE THREAD

**Issue by jnicholls** [clux/kube-rs#117]
According to https://github.com/kubernetes/kubernetes/issues/49745, there can be cases where watch events are streamed in with resourceVersions that are out-of-order. The Reflector implementation assumes the versions are always in order and does not perform a check before storing the next resourceVersion when enumerating a list of returned watch events.

e.g. https://github.com/clux/kube-rs/blob/master/src/api/reflector.rs#L223

Because the above Kubernetes issue went stale and was never actually addressed, and because there are at least 2 references to that issue from other Kubernetes client projects, I would suggest we add a simple check before we store an event's resourceVersion. PR incoming.

**Comment by clux** [comment]
Ah, we used to take a maximum before, but we are not really supposed to assume anything about the type of the `resourceVersion` (like whether or not it's an integer) because it's a etcd implementation detail. See https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions

**Comment by jnicholls** [comment]
Ok roger that. I suppose then we will let Kubernetes deal with this upstream.
