### ISSUE TITLE
Examples do not compile due to missing Api<K> implementations

### ISSUE THREAD

**Issue by jnicholls** [clux/kube-rs#119]
I believe this is from some refactoring of `Api<K>` and `RawApi` that must have happened in the past, before my introduction to this library. But, the examples assume a whole host of static methods on `Api<K>` that do not exist, but are instead present on `RawApi`.

I will submit a PR to add the methods to `Api<K>` as it would be a nice ergonomic addition and it would fix all of the examples.

**Comment by clux** [comment]
Most examples do require the **non-default** openapi feature. I have tried to highlight this in the README, but people do keep running into it.

**Comment by jnicholls** [comment]
Yes, I see. I was simply going by the default configuration and the result of that build. The way it is setup is clean, just unsuspecting to contributors compiling from source I suppose. I'll close this out but hopefully this issue will serve (if there weren't already other issues...I didn't search for closed ones, my fault if so!) as some documentation on the examples requiring the openapi feature.

_checks README..._

Maybe an additional README sentence under the *Examples* section would help. It's clear that the feature is enabled in the `cargo run` examples, but maybe something like:

> There are examples that show some of the most common use cases. All examples have logging of this library set to the `trace` level. _*NOTE: Most of the examples require the `openapi` feature to be enabled in order to compile. The `openapi` feature is not on by default!*_

**Comment by clux** [comment]
Yeah, I agree. We could probably highlight this better by default. Feel free to pr that sentence in :-)

**Comment by clux** [comment]
I have added a comment about it in two sections of the README. Maybe in the future we can change the default inclusion of features, but at the moment it is a bit awkward because the feature requires you to pick out another feature from the dependency it pulls in.
