### ISSUE TITLE
rustls auth_provider oauth support

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#120]
You will notice that the initial rustls support from #66 and #114, the oauth2 module was basically commented out leaving gke a bit unusable (or so I think).

Any help porting [src/oauth2/mod.rs](./src/oauth2/mod.rs) to rustls would be appreciated. It was mostly [ynqa's work from the original source tree](https://github.com/ynqa/kubernetes-rust), with some help from @davidB recently I think. But anyone feel free to jump on it. I have done the bare minimum to allow some clusters to at least work with rustls.

**Comment by NAlexPear** [comment]
>  leaving gke a bit unusable (or so I think)

Just confirmed that this :point_up: is the case while working on a GKE cluster using `load_kube_config()` and service account credentials. `RUST_BACKTRACE` shows an `unwrap` error on one of [these lines in the `into_token` method](https://github.com/clux/kube-rs/blob/master/src/oauth2/mod.rs#L100). 

The problem doesn't exist in version 0.6, so sticking with that version for now.

**Comment by clux** [comment]
Wait, is this the case default features? It should only affect `rustls-tls` installations.

**Comment by davidB** [comment]
I don't have GKE cluster, next week-end I'll re-setup a GKE cluster to take a look at this issue, and see If I can help

**Comment by NAlexPear** [comment]
I was running with the `openapi` feature only, but if this behavior is surprising, then I'll do my best to get you a more concrete repro later today.

**Comment by davidB** [comment]
@NAlexPear I was able to reproduce the issue with `into_token`, it was caused by a 400 response from gke during the refresh (I don't know why), the PR #123 includes display of the response from gke if response is not OK.

**Comment by clux** [comment]
Have released this PR in 0.25.0.

**Comment by clux** [comment]
This issue should have been closed a while ago.
As it stands the `rustls-tls` switches everything at the moment, and oauth for gcp is done via `tame_oauth` now.
