### ISSUE TITLE
unable to query config contexts

### ISSUE THREAD

**Issue by mattsawyer77** [clux/kube-rs#124]
I was wondering if it might be possible to expose the config utils module. My use case requires the ability to get a list of named contexts from the config. But if I'm reading the code right this is impossible.

**Comment by clux** [comment]
I think the `Config` struct is exposed. You could serialize the kube config file into that struct using `serde_yaml`. Although I think it's actually pretty reasonable to let users do this. We should just expose `Config::load_config`.

**Comment by clux** [comment]
Made a PR for this in #125 - might tweak it a bit. But we ought to have something like this.
