### ISSUE TITLE
Reflector::reset has an (admittedly unlikely) race condition

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#136]
`version` and `data` use separate mutexes. In most cases, either only one is used, or the `data` mutex is held for the duration of the `version` mutex. [However, `reset` releases `data` before grabbing `version`](https://docs.rs/kube/0.25.0/src/kube/api/reflector.rs.html#170-171), which can lead `version` to be reverted if `single_watch` (via `poll`) applies an update in between the two locks.

The practical effect of this would be that `poll()` restarts can get duplicate events (though they would just be no-ops).

**Comment by clux** [comment]
Thanks! Yep, this looks wrong. And it also doesn't look like there are any good reasons anymore to need two mutexes, so we should just combine their use.
