### ISSUE TITLE
apiextensions.k8s.io/v1beta1/customresourcedefinitions -> apiextensions.k8s.io/v1/customresourcedefinitions

### ISSUE THREAD

**Issue by debianmaster** [clux/kube-rs#137]
as CRDs promoted to apiextensions.k8s.io/v1 status in the latest release of k8s.
Any plan for this library to support latest crd spec?

**Comment by clux** [comment]
Yep, we support both in master if your openapi version is >= 1.17:

https://github.com/clux/kube-rs/blob/master/src/api/openapi.rs#L164-L184

**Comment by clux** [comment]
Released in 0.26.0
