### ISSUE TITLE
Remove implicit state from api::Api

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#150]
Most of this is redundant anyway..

- apiVersion/kind: Can be linked to `K` instead
   - This would also allow us to share a single `Api` instance, rather than setting up a separate `Api<K>` per resource type, which should make connection pooling easier
- namespace (write actions): can be inferred from object metadata 
- namespace (read actions): should probably be taken explicitly instead

**Comment by clux** [comment]
Yeah, happy to take improvements to this. Not super happy with the current setup either.

**Comment by teozkr** [comment]
One question remains though.. All `type FooMeta = Object<NotUsed, NotUsed>` aliases collapse into a single type. Maybe we should encourage newtypes instead?

**Comment by clux** [comment]
That might be good. I was thinking it would be nice to export a neater api tree:

```rust
api::{
  Api,
  corev1::{Pod, Node, Service},
  appsv1::{Deployment, StatefulSet}
}
```

**Comment by teozkr** [comment]
To me, the ideal would be that `kube-rs` is completely agnostic to the concrete resource types (stock or CRDs), and only cares about how to interact with the apiserver (and higher level patterns, like controllers). But that might not be completely realistic, given that it does need to interact with `metadata` a fair bit.

**Comment by clux** [comment]
Yeah. We did replicate the metadata structs from openapi so we didn't __have__ to be tied to it, so I don't think it's unrealistic. Metadata is the one main generic feature the kubernetes api actually has to abide by, so building helpers on top of that is useful (e.g. see [controllerutil](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/controller/controllerutil)).

**Comment by teozkr** [comment]
Agreed, but that brings the unfortunate case where raw pods require specifying a `kube::api::ObjectMeta`, but a `Deployment`'s `PodTemplateSpec` takes a `k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta`, with slightly different field types.

**Comment by clux** [comment]
fffffffffffffffffffffffffffffffffffffffff

**Comment by teozkr** [comment]
Sorry? D:

**Comment by clux** [comment]
being unprofessional, sorry. that just made me sad :-(

**Comment by teozkr** [comment]
Fair enough. Welcome to the club. :/

**Comment by teozkr** [comment]
Hm, then again, `k8s-openapi` seems to support CRDs these days, via [`k8s-openapi-derive`](https://docs.rs/k8s-openapi-derive/0.7.1/k8s_openapi_derive/derive.CustomResourceDefinition.html). It also already has metadata traits ([`Metadata`](https://docs.rs/k8s-openapi/0.7.1/k8s_openapi/trait.Metadata.html) and [`Resource`](https://docs.rs/k8s-openapi/0.7.1/k8s_openapi/trait.Resource.html)).

To me, most of the value of `kube-rs` is in:

1. The common `Api` interface, with a single API to generically perform any action on any `impl KubeObject` (`impl Resource + Metadata`)
2. The generic controller helpers that this enables (what is now the `runtime`)

Most of the rest is just boilerplate to marshal between `k8s-openapi` types and `kube-rs` types. Yes, `Object<Spec, Status>` feels neat, but generic code can't use it anyway (thanks to the snowflakes), and we lose the ability to associate `TypeMeta` with a type. And yes, `k8s-openapi` independence would be nice, but it's barely functional as is, and reminds me a lot of [XKCD 927](https://xkcd.com/927/), with a lot of boilerplate machinery to convert between the two.

Besides, if we do want to bring type-independence back, we could relatively easily make our own compatibility trait for only the components of `ObjectMeta` that we care about.. but `Object<Spec, Status>` is once again holding us back, by requiring all existing `Object`s to be adapted, rather than just adding a blanket `impl` for the `k8s-openapi` equivalent.

**Comment by clux** [comment]
> Hm, then again, `k8s-openapi` seems to support CRDs these days, via [`k8s-openapi-derive`](https://docs.rs/k8s-openapi-derive/0.7.1/k8s_openapi_derive/derive.CustomResourceDefinition.html). It also already has metadata traits ([`Metadata`](https://docs.rs/k8s-openapi/0.7.1/k8s_openapi/trait.Metadata.html) and [`Resource`](https://docs.rs/k8s-openapi/0.7.1/k8s_openapi/trait.Resource.html)).

I've only had a brief look at them so far, afaik they are pretty new. But they definitely look promising.

> Most of the rest is just boilerplate to marshal between `k8s-openapi` types and `kube-rs` types. Yes, `Object<Spec, Status>` feels neat, but generic code can't use it anyway (thanks to the snowflakes), and we lose the ability to associate `TypeMeta` with a type. And yes, `k8s-openapi` independence would be nice, but it's barely functional as is, and reminds me a lot of [XKCD 927](https://xkcd.com/927/), with a lot of boilerplate machinery to convert between the two.

Yeah. The boilerplate to do the mapping does really put a dent in the abstraction's usefulness. I'm not too attached to it.

> Besides, if we do want to bring type-independence back, we could relatively easily make our own compatibility trait for only the components of `ObjectMeta` that we care about.. but `Object<Spec, Status>` is once again holding us back, by requiring all existing `Object`s to be adapted, rather than just adding a blanket `impl` for the `k8s-openapi` equivalent.

Yeah, if there's a good `k8s-openapi` equivalent, then blanket impls might be a better approach.

I used to think that `Object<Spec, Status>`, while not applicable for all original kube api types, had some value. It is what all k8s maintainers kept saying that this is what the world should look like, and what all new objects are designed for. And by forcing users through this for CRDs, then at least, we are enforcing best practices (preventing further snowflake creation). Now.. Not so sure anymore.

If you want to make some sweeping changes, go for it. I agree with all you're saying here, and would like to see what you're envisioning :smile:

**Comment by clux** [comment]
Omg. The `Resource` trait would have been so useful if I had known about it a week ago :((
Yeah, totally we can just rip out a huge part thanks to that.

**Comment by clux** [comment]
Small complication in moving over to these traits: https://github.com/Arnavion/k8s-openapi/issues/60

**Comment by teozkr** [comment]
Well, we could make our own `MetadataContent` trait and `impl` it for both of their cases. That should be fine with the orphan rule as long as we own at least one of the types mentioned (the trait, in this case).

**Comment by clux** [comment]
Ohhh. Doh. Yeah, that would totally work.

**Comment by clux** [comment]
Ok. I have something that gets part of the way there:


```rust
#[cfg(feature = "openapi")]
impl<K> From<K> for RawApi
    where K: k8s_openapi::Resource
{
    fn from(k: K) -> RawApi {
        RawApi {
            api_version: K::API_VERSION.to_string(),
            kind: K::KIND.to_string(),
            group: K::GROUP.to_string(),
            version: K::VERSION.to_string(),
            namespace: None,
        }
    }
}
```

by majorly changing the `RawApi` interface. Not thinking about the potential namespace improvement yet (since it's already world-changing enough to get this to compile).

Going to play around a bit with it to see what implications this has for the rest of the code-base. Probably getting a PR up tomorrow.

**Comment by clux** [comment]
Ok. Before discuss another problem, I would like to take a small moment to celebrate that despite having ripped out all the snowflake code and all the internal k8s_ codegen macros from openapi.rs, the branch works, and we can technically build informers/reflectors on top of any `k8s_openapi` struct that uses its own `ObjectMeta`.

However, the `Metadata` issue took me a quite a while to get around. Here's how it stands atm:

We now have an ambiguous trait:

```rust
/// A trait that used to be called KubeObject, but now extended
#[cfg(not(feature = "openapi"))]
pub trait Metadata {
    /// The metadata type (typically ObjectMeta, but sometimes ListMeta)
    type Ty;
    /// Every object must have metadata
    ///
    /// But to match k8s_openapi::Metadata, we pretend it's optional
    fn metadata(&self) -> Option<&Self::Ty>;
}

/// Make sure they are have similar use cases
#[cfg(feature = "openapi")]
pub use k8s_openapi::Metadata;

```

^ this makes sure we are only ever exposing one `Metadata` trait regardless of features.
Then, a new accessor trait that is used everywhere in the `runtime` in place of `KubeObject`:

```rust
pub trait MetaContent: Metadata {
    fn resource_ver(&self) -> Option<String>;
    fn name(&self) -> String;
    fn namespace(&self) -> Option<String>;
}

#[cfg(not(feature = "openapi"))]
impl<K> MetaContent for K
where
    K: Metadata<Ty = ObjectMeta>,
{
    fn resource_ver(&self) -> Option<String> {
        self.metadata().unwrap().resourceVersion.clone()
    }
    fn name(&self) -> String {
        self.metadata().unwrap().name.clone()
    }
    fn namespace(&self) -> Option<String> {
        self.metadata().unwrap().namespace.clone()
    }
}

#[cfg(feature = "openapi")]
impl<K> MetaContent for K
where
    K: k8s_openapi::Metadata<Ty = k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta>,
{
    fn resource_ver(&self) -> Option<String> {
        self.metadata().unwrap().resource_version.clone()
    }
    fn name(&self) -> String {
        self.metadata().unwrap().name.clone().unwrap()
    }
    fn namespace(&self) -> Option<String> {
        self.metadata().unwrap().namespace.clone()
    }
}
```

This means we can technically still use kube with CRDs without the full `k8s-openapi` dependency.
However there is now new magic in there to switch the underlying `ObjectMeta` definition. If you're not on the `openapi` feature, you get our hand-written `ObjectMeta` (with a lot less optionals and camelCase). So if you did decided you suddenly need to upgrade to the other feature, your old code could stop working (until you fixed cases and added unwraps).

Because of this, I am considering just dropping `ObjectMeta` from this crate, but that means we hard-couple ourselves to `k8s-openapi` - even if we never have to use anything except `ObjectMeta`. I doubt I would care so much about this if it wasn't so heavy weight, or if there was a sub-crate that had just:

- TypeMeta
- ObjectMeta
- Metadata + Resource traits (and any other generic stuff)

**Comment by clux** [comment]
Think I am going to pull in the `k8s-openapi` as a permanent dependency (without the default `api` feature). This does mean a slight compile time hit, but it does not seem particularly severe to be worth worrying about. Debated asking upstream, but having measured a bit, I am less concerned.

It's probably a good idea to rip out metadata.rs entirely.
