### ISSUE TITLE
OAuth JWT missing exp claim

### ISSUE THREAD

**Issue by NAlexPear** [clux/kube-rs#156]
The OAuth request to Google Cloud Platform (endpoint `https://oauth2.googleapis.com/token`) in the `oauth` module was failing with the following response from Google:

```
{"error":"invalid_grant","error_description":"Invalid JWT: exp (expiration time) is not set."}%
```

This makes sense, since the current `oauth` module includes an `iat` in the `Claims` struct, but no `exp`. I've created PR #155 to solve the issue.

**Comment by clux** [comment]
Good find. Thank you!

Will release in the next version this weekend (hopefully).
