### ISSUE TITLE
A spot for chat

### ISSUE THREAD

**Issue by xrl** [clux/kube-rs#166]
Any interest in getting a channel somewhere? Perhaps discord? We could get on the tokio discord server and have a channel in the `libs` group.

It'd be nice to chat with users, share tips, discuss friction points, etc.

**Comment by teozkr** [comment]
Would Matrix or Gitter work? I try to avoid Discord at work.

**Comment by xrl** [comment]
The only reason I bring up discord is that rust and tokio have active groups on there. I don't really want another app, so I'm happy to get off discord. I think Matrix is the official Mozilla stack but Rust isn't on it (yet?).

Here's the mozilla post: https://discourse.mozilla.org/t/synchronous-messaging-at-mozilla-the-decision/50620

**Comment by clux** [comment]
Yeah, I tried to use gitter and always failed to. I like the tokio discord, am often on it, but not sure they'll give us a channel on their discord? Would be nice though, I see a ton of the same people on there.

**Comment by xrl** [comment]
We have a #kube channel in the tokio discord. Well received and people are chatting already! See you there!

**Comment by teozkr** [comment]
The invite link on tokio.rs seems to be broken. :/

**Comment by xrl** [comment]
How about... https://discord.gg/tokio ?

**Comment by teozkr** [comment]
That's the one.
![image](https://user-images.githubusercontent.com/649832/76017223-8c8e1200-5f1e-11ea-8442-645c7ba34b96.png)

**Comment by xrl** [comment]
Also, closing this ticket was probably premature. I should add info to the README.md. Please confirm that invite link works and then I'll open a PR to document it.

**Comment by xrl** [comment]
Reopening. I'll close this when the invite links works and I have added it to the kube-rs README.

**Comment by clux** [comment]
I can invite with https://discord.gg/ceFXZJ but invite links expire in a day.

**Comment by xrl** [comment]
Lucio on discord got back to me, https://discord.gg/tokio appears to work again. At the very least I do not get the 💩 message.

**Comment by clux** [comment]
Closed by #168
