### ISSUE TITLE
Derived CustomResource objects do not contain a TypeMeta

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#170]
This prevents using them to write to the K8s API.

**Comment by teozkr** [comment]
k8s-openapi seems to solve that by implementing `serde::Deserialize` manually.. https://docs.rs/k8s-openapi/0.7.1/src/k8s_openapi/v1_17/api/core/v1/secret.rs.html#625-626

**Comment by clux** [comment]
Ah, we can just flatten TypeMeta in there like we did with the old type. Provided we make some nice way of making a `Foo::new()` (#167)
