### ISSUE TITLE
Make Api::apply as an alias for Api::patch with server-side mode

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#174]
So we have a nice interface to server-side apply (limit to kubernetes version >=1.16)

**Comment by clux** [comment]
Perhaps [Api::update](https://kubernetes.io/docs/reference/using-api/api-concepts/#apply-and-update) would also be a useable name, given there are two ways to do it.

**Comment by clux** [comment]
A potential, require the whole `K` and have as a shorthand replacement for `Api::replace`:

```rust
    /// Server side apply a yaml patch over a named resource
    ///
    pub async fn apply(&self, name: &str, patch: &K) -> Result<K>
    where
        K: Serialize,
    {
        // TODO: ApplyParams shorthand? for now...
        use crate::api::PatchStrategy;
        let ssapply = PatchParams {
            patch_strategy: PatchStrategy::Apply,
            // always override on conflicts
            force: true,
            // owner of the fields: (us)
            field_manager: Some(env!("CARGO_PKG_NAME").into()),
            ..Default::default()
        };
        let bytes = serde_yaml::to_vec(&patch)?;
        let req = self.api.patch(name, &ssapply, bytes)?;
        self.client.request::<K>(req).await
    }
```

Now of course this does not let people supply partial patches like the `PatchParams::default` (json merge) lets you. But this is actually kind of good at the moment, because kubernetes will force any optionals on our `K` to null if we leave them out (even if they are missing from the serialization). I.e. 
 you actually force options to None even if they were set before if you miss them out.

So lacking a good solution to #129 (which I think would let us customize that behaviour / hook it into our serde skip_serialize behavior), it's not a good plan to let people supply partial yaml to server side apply on CRDs. If they need partial application, they need to stick with json merge until we have support for that.

**Comment by clux** [comment]
This is probably a mistake. Going to just do this with a constructor alias on PatchParams.

**Comment by teozkr** [comment]
Yeah.. `apply` and `patch` have vastly different types ([`Partial<K>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialt) and `JsonPatch<K>` respectively, though neither can be expressed natively in Rust today).
