### ISSUE TITLE
subset serialization and Object

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#183]
Before the last minor, it was quite easy to allow one defined Api type to be deserialized into less strict structs:

```rust
type FullManifest = Object<Manifest, ManifestStatus>;
type MinimalManifest = Object<ManifestSmall, ManifestStatus>;
```

then we could make another `Api` or `Resource` (then `RawApi`) object from one of these. My use case here is that I do not always want to model everything all the time (need to be resilient against schema changes, so parsing needs to work regardless of breaking changes, so must fall back to parsing a very tiny subset).

Now it's less trivial. We got to `#[derive(CustomResource)]` twice with same params on two structs (which is non-trivial since it tries to create a struct with name == Kind). If we don't do that then  we gotta use the `Resource` interface, but to do this we basically force people to recreate the old `Object<Spec, Status>` downstream. If this is useful, I'd rather have the abstraction in here.

As such, am considering re-introducing `Object` for serialization purposes. It is useful for a few other cases like this, and it wouldn't clash with the current setup much because it doesn't natively implement `k8s_openapi::Resource` or `k8s_openapi::Metadata`. But still coming across old code that used `Object` that I find awkward to replace.

Of course we could do something liken `Api::get_subset::<MySubset>` method, but that feels a bit confusing for same reason we closed #172.

**Comment by teozkr** [comment]
Wouldn't it be easier to allow overriding the name of the derived kind struct?

**Comment by teozkr** [comment]
Alternatively.. just stick them in different modules and use the qualified names?

**Comment by clux** [comment]
You can do that, but there's 7 different `#[kube(attr)]` fields on it + 1 root `#[derive]`. Would need to duplicate at least 4 lines of this proc_macro stuff just to have an alias (and run the proc macro again at compile time every time). I'd rather not duplicate when there's a working solution.

But even if we're doing that it doesn't help in the ad-hod deserialization case where we don't even have a kube object and want to read a bunch of kinds (like from helm template output). `Object` fit this role perfectly.
