### ISSUE TITLE
Do you need to support v1.8, v1.9 and v1.10 ?

### ISSUE THREAD

**Issue by Arnavion** [clux/kube-rs#188]
I want to drop them from `k8s-openapi` in 0.8.0

The primary reason is that I want to use `kind`'s docker-based clusters instead of `minikube`'s VM-based clusters for testing. I can run `kind` clusters for all supported versions simultaneously without running out of RAM, which makes it easier to iterate on changes. `kind` only supports v1.11+, so I'm using it as an excuse to drop v1.10 and earlier.

**Comment by clux** [comment]
Yeah, that's reasonable. We don't really support those old versions.

We assume basic CRD functionality (which is like >=1.12 already), and the minimum EKS and GKE versions are also 1.12 and 1.13, so that's the minimum we can reasonably target for future releases.

**Comment by Arnavion** [comment]
Cool. Thanks.
