### ISSUE TITLE
CRD Informer

### ISSUE THREAD

**Issue by sstubbs** [clux/kube-rs#189]
Hi,

I have a project I'm upgrading based on this https://github.com/technosophos/rust-k8s-controller/blob/master/src/main.rs. However there have been quite a lot of changes to this project and I can't find an example of how to do it. Everything else works well I can derive and receive the event based on this example https://github.com/clux/kube-rs/blob/master/kube/examples/crd_api.rs but I can't cast the actual event to the the derived struct to handle it.

How would you suggest I do this?

**Comment by sstubbs** [comment]
I'm trying to use the derived struct in this line instead of KubeBook with no luck. https://github.com/technosophos/rust-k8s-controller/blob/acb5886da248eec33eedd233c06a31e82bf250f0/src/main.rs#L49

**Comment by teozkr** [comment]
Not sure what you mean by "cast the actual event to the derived struct". Do you have a dump of your conversion so far?

**Comment by sstubbs** [comment]
Sorry if I wasn't clear.

I have the following code:
```
#[derive(CustomResource, Deserialize, Serialize, Clone, Debug)]
#[kube(group = "domain.com", version = "v1beta", namespaced)]
pub struct PostgresXlClusterSpec {
    pub data: Option<String>,
}

pub async fn watch() -> anyhow::Result<()> {
    let config = config::load_kube_config().await?;
    let client = APIClient::new(config);
    let namespace = std::env::var("NAMESPACE").unwrap_or(NAMESPACE.into());

    let resource = Resource::namespaced::<PostgresXlCluster>(&namespace);
    let inf = Informer::new(client, ListParams::default(), resource);

    loop {
        let mut resources = inf.poll().await?.boxed();

        while let Some(event) = resources.try_next().await? {
            handle(event)?;
        }
    }
}

// This function lets the app handle an event from kube
fn handle(ev: WatchEvent<PostgresXlCluster>) -> anyhow::Result<()> {
    match ev {
        WatchEvent::Added(o) => {

        }
        WatchEvent::Modified(o) => {

        }
        WatchEvent::Deleted(o) => {

        }
        WatchEvent::Error(e) => {

        }
    }
    Ok(())
}
```
and I'm getting this error.

```
2020-03-14T23:14:34Z WARN  kube::client] Failed to parse: 404 page not found
[2020-03-14T23:14:34Z WARN  kube::runtime::informer] Unexpected watch error: SerdeError(Error("invalid type: integer `404`, expected adjacently tagged enum WatchEvent", line: 1, column: 3))
Error: Error deserializing response

Caused by:
    invalid type: integer `404`, expected adjacently tagged enum WatchEvent at line 1 column 3
```
is `fn handle(ev: WatchEvent<PostgresXlCluster>) -> anyhow::Result<()> {` the correct way to use this?

**Comment by teozkr** [comment]
Ah. Sounds like you forgot to install the `CustomResourceDefinition` into your cluster, so your controller is asking for a `Kind` that your APIServer doesn't know about.

**Comment by teozkr** [comment]
If you have written a CRD manually, you can just install it. If not, `kube-derive` has generated a `PostgresXlCluster::crd()` method that you can use to generate one.

**Comment by sstubbs** [comment]
I do have a bash script creating the crd from when the previous version of kube-rs was installed but I must have a mismatch in name somewhere. That's great that the crd can be created so easily from within the app now. Thanks a lot for the help.

**Comment by sstubbs** [comment]
I can confirm this works perfectly and this issue can be closed.
