### ISSUE TITLE
Replace std::thread::sleep in example

### ISSUE THREAD

**Issue by sstubbs** [clux/kube-rs#190]
Hi based on the example I have the following to create a crd:

```rust
pub async fn create_crd(client: APIClient) -> anyhow::Result<()> {
    // Manage CRDs first
    let crds: Api<CustomResourceDefinition> = Api::all(client.clone());

    // Delete any old versions of it first:
    let dp = DeleteParams::default();
    // but ignore delete err if not exists
    let _ = crds.delete("groups.vdb.domain.com", &dp).await.map(|res| {
        res.map_left(|o| {
            info!(
                "Deleted {}: ({:?})",
                Meta::name(&o),
                o.status.unwrap().conditions.unwrap().last()
            );
            // NB: PropagationPolicy::Foreground doesn't cause us to block here
            // we have to watch for it explicitly.. but this is a demo:
            std::thread::sleep(std::time::Duration::from_millis(1000));
        })
        .map_right(|s| {
            // it's gone.
            info!("Deleted groups.vdb.domain.com: ({:?})", s);
        })
    });

    // Create the CRD so we can create Groups in kube
    let groupcrd = Group::crd();
    info!(
        "Creating Group CRD: {}",
        serde_json::to_string_pretty(&groupcrd)?
    );
    let pp = PostParams::default();
    match crds.create(&pp, &groupcrd).await {
        Ok(o) => {
            info!("Created {} ({:?})", Meta::name(&o), o.status.unwrap());
            debug!("Created CRD: {:?}", o.spec);
        }
        Err(kube::Error::Api(ae)) => assert_eq!(ae.code, 409), // if you skipped delete, for instance
        Err(e) => return Err(e.into()),                        // any other case is probably bad
    }
    // NB: PropagationPolicy::Foreground doesn't cause us to block here
    // we have to watch for it explicitly.. but this is a demo:
    std::thread::sleep(std::time::Duration::from_millis(1000));
    Ok(())
}
```
It works well so far but I need to use thread::sleep twice for it to work properly. Not the end of the world as it only happens when the app runs initially but is there a better way?

**Comment by teozkr** [comment]
In the real world you'd probably want to install the CRD statically, together with your controller's `Deployment`. Otherwise you could get into annoying versioning fights during upgrades.

If you still want to use `kube-derive`s CRD generator then you could set up a [secondary bin](https://doc.rust-lang.org/cargo/guide/project-layout.html) that dumps the CRD YAML to some file (or stdout).

**Comment by clux** [comment]
You don't really wan't to delete and re-apply the CRD everytime you boot becuase that kills all the custom resource instances. You could use `replace` on it if you want to ensure it's up to date - or server-side apply. You might still have to wait for it to have been properly created, in either case? Haven't tested server-side apply too much. There are some bugs still around them.

**Comment by sstubbs** [comment]
ok thanks I noticed it killing the instances. I will try this some more with the replace like you suggest. I like the idea of needing less external YAML files. Otherwise dumping it and loading in the yaml file is also an option as that's what I was doing before. At least now I can be sure the CRD YAML is up to date if it's dumped from the app whereas before I was manually creating it. Thanks a lot for the help.

**Comment by clux** [comment]
The crd_apply example now shows how to do an idempotent apply using server-side apply and waiting for it properly via a `watch` call: https://github.com/clux/kube-rs/blob/master/kube/examples/crd_apply.rs#L105-L131

Note that we haven't replaced all the other sleeps in examples, because doing it properly adds a bit an extra 25 lines of code.
