### ISSUE TITLE
Cannot build on Windows with native-tls

### ISSUE THREAD

**Issue by stephenc** [clux/kube-rs#197]
Seems to be some hard-coded assumptions that openssl is present for native-tls

**Comment by stephenc** [comment]
Example failure: https://github.com/stephenc/k8s-gcr-auth-helper/runs/536724526?check_suite_focus=true

**Comment by teozkr** [comment]
According to https://docs.rs/openssl/0.10.28/openssl/#automatic it should pick up openssl if you install it with [vcpkg](https://github.com/Microsoft/vcpkg).

**Comment by clux** [comment]
Did you disable default features?

**Comment by stephenc** [comment]
So I'm having a very tough time getting to compile across all environments that I need to build for. If I use rustls then it turns on strict host checking. I've been trying to avoid setting up a dedicated build environment for windows but I guess I'll need to do that to get openssl to work

**Comment by clux** [comment]
Closing this old issue, there's been a lot of work straightening out TLS. I suspect this might not have been broken in the first place from the comments, but our windows testing is also a bit limited. Please re-open if problems persist.
