### ISSUE TITLE
List at KUBECONFIG is not properly supported

### ISSUE THREAD

**Issue by MOZGIII** [clux/kube-rs#198]
Here's a sample `KUBECONFIG` in a list form:

```
/home/user/.kube/config:/home/user/.kube/config.d/a::/home/user/.kube/config.d/b
```

It's expected to be loaded as a single merged object.

Instead, `kube` it fails to load it with `failed to load kubeconfig: Error { inner: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

**Comment by teozkr** [comment]
Closing this as a duplicate of #132. That issue also contains a workaround (annoying as it is.. :/).

**Comment by MOZGIII** [comment]
Sorry, I couldn't find that one :+1:
