### ISSUE TITLE
Factor out config + oauth module

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#204]
Into a kube-config crate that has an oauth feature. That way people who just need to parse the kube config, don't need to pull in reqwest.

**Comment by clux** [comment]
Will probably do one release of kube before doing this.

**Comment by clux** [comment]
Having thought about this some more now that we're merging in kube-rt in #258 , there's actually another problem that this solves. `kube-runtime` depends on `kube` (api part only), but because kube has the client and the config, it needs to choose a tls impl (which makes testing awkward and causes features to multiply). So kind of need to solve this now.

Had put this on hold because it was actually kind of awkward to split the Config and Client due to a cycle and no real sensible boundary interface. Thinking  the solution here is to make a crate that contains both the config and the client (and make the client part a default feature).

This means we still need a boundary interface between the api and the client. Perhaps trait out the methods we implement in client/mod.rs. Either as a separate traits crate, or just have the client/config crate depend on the api. That feels like a sensible direction on the face of it at least.

Though we would still need a dev-dependency on this crate to run any kind of tests so we still need to select a tls impl, so there's still the potential for features to multiply, but that might be fixed by having the examples folder as a separate crate.

This is very much thinking out loud at the moment. Trying to get #258 publishable first.

**Comment by clux** [comment]
Have published kube-runtime at this point. It also has to do tls feature selection in `kube` even if it just depends on `kube::api`.
Going to look at this again.

**Comment by clux** [comment]
Definitely need a solution to #278 first as well as a sensible dependency schema.

So far we got:

- kube-runtime depends on kube (only api parts)
- dev-dependenciens of each other

If we wanted to re-export crates then we would have a cyclical dependency graph:
- kube-runtime depending on kube
- kube reexporting runtime in the place where the old runtime was causes dependency on kube-runtime

A future potential would be to create 2 new crates: kube-api and kube-config (which also contains the client optionally):

- kube-runtime depends on kube-api
- kube-api depends on kube-config (combo crate)
- kube depends on kube-api + kube-config + kube-runtime + kube-derive and re-exports all under features
- many dev-dependency friends

The last one is the most ergonomic for users of the project, but due to #278 is a pain to release.

**Comment by teozkr** [comment]
Yeah.. IMO the last one makes sense. Maybe also consider moving the examples into each layer, rather than the current devdep spaghetti (so `kube`/`kube-api` shows how to query the API directly, `kube-runtime` has a few example controllers, etc). `cargo-release` seems to have a sensible workflow IMO, but I'm not familiar enough with it to know what gotchas are lurking behind the surface.

**Comment by clux** [comment]
Unfortunately, the 5 crate solution would have even more spaghetti. kube-runtime would depend on kube-api which would depend on kube-config, to we'd need sequential publishing, and people aren't able to swap out any of the lower end crates anyway. I'm starting to think there's not much to be gained unless we can make the interfaces be clearly delineated in modules as a starting point anyway.

Because of #278 - I don't want to do the 5 crate solution atm. It would either make the release scripts brittle (hardcoding dependency cases), or severely slow down the release process.

Therefore, I suggest we work on standardising the error handling, then we can introduce a `runtime` feature to `kube`, which will add kube-runtime as a module and drop the old runtime module. We already know that boundary is clean. It depends on `kube`. But it can be a purely additive feature.

I'd much rather go for a tokio style repo with an examples part of the workflow list, and a better set of features.

**Comment by clux** [comment]
Ok, so we had a long listing of pros/cons on discord about this. Turns out #278 is workable in the current 3 crate setup (even if it `cargo-release` gets confused by dev-deps).

Now personally, I still don't think it's going to be great in a 5 crate setup with dev-dep soup, so probably going to have to look at config/client as features on kube and investigating a sans-io approach within kube first before any splitting/conglomeration issue is re-raised. If we can't split things within modules using features, we can't do it with crates anyway.

Noting down some points from the discussion from my POV.

#### why the big feature crate is hard/awkward

- multiplicative testing required (need to test all combos for mutually exclusive features)
- editors getting confused by features (particularly mutually exclusive ones like rustls-tls vs native-tls)
- `kube-runtime` and `kube` are not really in the same stability land (even though they are versioned together)

The last one means that your versioning guarantee needs to be the worst of your modules. Not that it means much at the moment since every release is a pre-1.0 minor, but we do hope to stabilise at one point.

#### potential arguments against big feature crate

- multi-crate better for parallel builds
- `cargo-edit` arguably makes it easier to modify dependencies via cli than editing feature sets in `Cargo.toml`

2. The last one surface I agree with, but it would expose the full dependency tree of crates to users.

#### why multi-crate is hard/awkward:

- release process is still going to be hard with `cargo-release` due to dev-dep spaghetti
- might need tiny crates for traits and interfaces with its own version so crates can be truly independent
- users must maintain consistent dependency versions of their tree because we build them together
- need to test mutually exclusive features anyway
- crates need to re-export features from other crates (rustls need to be configured in both kube and kube-runtime)

Feature + dependency issues is one of the main reasons I dislike many crates. If you can only configure these two values in one place, you eliminate an entire class of errors (less hard to debug issues on this repo).

**Comment by clux** [comment]
Way forward will probably be to close this issue and make others for:

Investigate better a way to make client/config/api less dependent on each other with modules and well defined interfaces.
See if if a sans-io approach like via tower #100 would help with that.

Maintain kube/kube-runtime split even if it means we cannot re-export the runtime from `kube`. Which is fine at the moment. We could still re-export `kube-derive` from `kube` under a feature.

Consolidate error handling herein with `snafu`. This at least gives us a consistent interface, less overall dependencies, and it would be required for any kube/kube-runtime consolidation anyway.

**Comment by kazk** [comment]
The boundaries will be much more clear with #376. We should have sans-io client if we introduce a feature for the default service implementation.

For errors, I haven't used `snafu`, but I like their philosophy

> Each module should have one (or more!) error types that are scoped to that module, reducing the need to deal with unrelated errors when matching and increasing cohesiveness of a single error type.
> https://docs.rs/snafu/0.6.10/snafu/guide/philosophy/index.html#many-error-types

**Comment by clux** [comment]
Opened #406 about how to proceed from here. With `cargo-release` being a lot better, and modules a lot more cleanly delineated, let's have a discussion about the module edges first before we potentially progress to more crates (if at all).
