### ISSUE TITLE
tokio::signal is used but tokio signal feature is not enabled

### ISSUE THREAD

**Issue by jbg** [clux/kube-rs#223]
Adding this crate as a dependency to a project that doesn't already depend on `tokio` with the `signal` feature enabled results in this crate failing to compile, because this crate uses `tokio::signal` but doesn't enable the `signal` feature on its `tokio` dependency.

**Comment by clux** [comment]
Thank you, that is a mistake indeed. Will make a patch release for it.

**Comment by clux** [comment]
Released in 0.32.1
