### ISSUE TITLE
should be able to set path of `client.config' explicitly

### ISSUE THREAD

**Issue by jobenye** [clux/kube-rs#230]
Not all `client.config` is located in "~/.kube/". For example, in microk8s installed cluster, the file is located in "/var/snap/microk8s/current/credentials".

Currently `Config::new_from_kubeconfig()` can't specify the file path and `ConfigLoader::load()` is defined as internal ctor. Therefore the only way to create `Config` is by `Config::new()` and fill the fields manually.

The `struct Kubeconfig` is published, but look's like no other methods to utilize the result of `Kubeconfig::read_from()`.

**Comment by clux** [comment]
Thanks for the report. That might be worth exporting something better for. In the mean time, we do pick up on the `KUBECONFIG` evar, maybe setting that will work?

**Comment by jobenye** [comment]
Yes, the env `KUBECONFIG` works. It could be a workaround. Thanks.

**Comment by clux** [comment]
This was fixed in #236 . Together with the available evar, will mark this as closed in the next minor.

**Comment by clux** [comment]
Which was 0.35.X.
