### ISSUE TITLE
Patch strategy support

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#24]
Currently `Api::patch` and similar only support `--type=merge` (i.e. `.header("Content-Type", "application/merge-patch+json")`). 

Would be good to support [the 3 strategies](https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/#use-a-json-merge-patch-to-update-a-deployment).

Note that CRDs doesn't seem to support strategic merge atm, so need better tests. See https://github.com/kubernetes/kubernetes/issues/52772.

**Comment by ragne** [comment]
Hi, I'd like to tackle on the issue. How resulting api should look like? 

- The simple idea is to add another parameter (enum) to `Api::patch` but it doesn't sound that great, though.
- Second one is to add that parameter to `PostParams` (create another struct `PatchParams`?) and check in `Api::patch` like it was done for `dry_run`?

**Comment by clux** [comment]
Hey, awesome! Please go right ahead.

I totally agree with the `PatchParams`, it's already close to what's in kubernetes under [meta/v1#PatchOptions](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#PatchOptions).

**Comment by clux** [comment]
Funnily enough though, client-go still passes in an enum and a PatchOptions object :confused:
https://github.com/kubernetes/client-go/blob/e6a502f77fded2b9d038629506553ae5bb6e0388/dynamic/client_test.go#L641
