### ISSUE TITLE
How to list all contexts in kubeconfig ?

### ISSUE THREAD

**Issue by maver1ck** [clux/kube-rs#261]
`kubectl config get-contexts` gives possibility to list all contexts in `.kube/config`.

How to achieve this behaviour using kube-rs ?

**Comment by clux** [comment]
Check out https://docs.rs/kube/0.35.1/kube/config/struct.Kubeconfig.html

let conf = Kubeconfig::read()? -> do stuff with `conf.contexts`

**Comment by maver1ck** [comment]
Thanks :)
