### ISSUE TITLE
TLS woes

### ISSUE THREAD

**Issue by sdlarsen** [clux/kube-rs#263]
I'm unsure if this is addressed in any other issue (https://github.com/clux/kube-rs/issues/132 for instance), but my setup is fairly simple:
k8s oauth to github with dex/gangway. The certificate is valid (production cert from letsencrypt). 
When trying to connect with the client setup using `let client = Client::try_default().await?;` I get:

`Error: ReqwestError: error sending request for url (https://my-cluster/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/collections.blah.test?&force=true&fieldManager=test-operator): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913: (unable to get issuer certificate)

Caused by:
    0: error sending request for url (https://my-cluster/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/collections.blah.test?&force=true&fieldManager=test-operator): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913: (unable to get issuer certificate)
    1: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913: (unable to get issuer certificate)
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913: (unable to get issuer certificate)
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:`

Any suggestions? No other tool I've tried refuses to use my current config, so I'm a bit suprised :)

**Comment by clux** [comment]
Hard to tell from just that output. Oauth providers have always been hard for us to test, but it looks like you're beyond that stage. Then again we're not really doing a lot of magic to the certs. Does the problem persist with openssl as the tls stack?

**Comment by teozkr** [comment]
FWIW, if this is for local testing then you could use `kubectl proxy` as a workaround, to let kubectl handle all of the OAuth/TLS stuff for you.

**Comment by sdlarsen** [comment]
@clux I've tried with "native-tls" and "rustls-tls". It seems not to make any difference. And that output is all I get :)
@teozkr, I'll try using kubectl to proxy it for my testing, thanks!

**Comment by sdlarsen** [comment]
@teozkr Using kube proxy works fine for testing. But moving to the cluster gives me much the same situation.

Using a plain `client = Client::try_default().await?` gives me similar output:
`Error: ReqwestError: error sending request for url (https://10.3.0.1/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/collections.blah.test?&force=true&fieldManager=test-operator): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get issuer certificate)

Caused by:
    0: error sending request for url (https://10.3.0.1/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/collections.blah.test?&force=true&fieldManager=test-operator): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get issuer certificate)
    1: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get issuer certificate)
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get issuer certificate)
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915:
`

From the pod describe I see the sa is mounted:
`Volumes:
  solr-operator-sa-token-dn6jg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  test-operator-sa-token-dn6jg
    Optional:    false
`

And to make sure I didn't miss any permissions, the sa is bound to cluster-admin. I'm running with native-tls-vendored.

Suggestions are welcome :)

**Comment by teozkr** [comment]
@sdlarsen What does your `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` contain? Is `curl https://10.3.0.1/ --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt` able to connect?

**Comment by sdlarsen** [comment]
Yes, I can connect with curl, but only if I add --insecure as the cluster certs are self-signed, which seems to be the issue (for both environments actually). 
Sorry for bothering you with this. The current solution is:
`
     let mut config = Config::infer().await?;
     config.accept_invalid_certs = true;
     client = Client::new(config);
`
Which I think is the correct way with self-signed certs?

**Comment by teozkr** [comment]
No, it should allow the connection if you specify the correct CA explicitly (via `--cacert`). That cURL doesn't work either makes it sound like a cluster issue, where it mounts the wrong CA into the pods for some reason, or the cert is invalid for some other reason (expired? incorrect clock?).

**Comment by sdlarsen** [comment]
True, something is off with the certs. Let me fix that and get back to you.

**Comment by sdlarsen** [comment]
True, fixing the cert setup solved that. Thank you for the assistance.
