### ISSUE TITLE
How to handle invalid custom resource in an Informer?

### ISSUE THREAD

**Issue by praveenperera** [clux/kube-rs#265]
If a user uploads an invalid CR, one that can't be serialized into a struct, how should I handle this?

In the informer examples the app would just exit, if I call it in a loop I get SerdeError over and over again and I don't receive new events. 

Is it possible to emit a `WatchEvent::Error` on `SerdeError`?

If the user uploads an invalid CR, I want to let, delete the CR, let the user know its invalid and continue listening for the next event.

**Comment by clux** [comment]
If you have an Informer on the event I believe you unpack the `Result` and act on the `Err(e)` when `e` is a `SerdeError` and then maybe manually parse it with serde_yaml speculatively for some key propreties.

Other than that, having kubernetes or something else validate the schema of your CRD so that you don't get into that situation within the controller is the ideal way to go.

**Comment by praveenperera** [comment]
Hey @clux, thanks for helping.

I tried listening to the events but it didn't get triggered on CR adding, deleting etc.

I tried unpacking the Result when I was calling the informer with my custom CR type. But since I was calling `inform.poll()` in a loop, the the invalid CR would trigger again and again. It would get stuck in a loop, and it wouldn't pass along other events.

I thought it might be because of on error version isn't updated here: https://github.com/clux/kube-rs/blob/master/kube/src/runtime/informer.rs#L148-L153

So it doesn't know that its already been looked at and dealt with? 

I also tried listening to `CustomResource` with my group attributes using CRBuilding. But I couldn't use that with the Informer because it didn't implement `Meta` type.

**Comment by clux** [comment]
Oh, crap. Yeah, this might be a bit of an edge case in here after all. Normally we deal with typesafe structures all the way so have not really tried out this path... It looks like you might be right in that it causes the poll to restart from the last cached resource_version (even if this is not ideal). Not sure what's a good solution here atm. Not super keen on extending `WatchEvent` with special error cases, but if we just make the Error type in `Result<WatchEvent, Error>` case contain a better `Error` (i.e. making the current error type more parseable) then the Informer's poll will still end..

Some thoughts: 

- For type safety we need to return `WatchEvent<K>` where `K` matches your  object exactly, so you have to end up in an Err and not an Ok. But we can let you not have to parse the ad-hoc error struct by defining a proper error subtype.

- Type safety is one of the contracts you sign up for in rust. Your object needs to match the Spec you write. Validation should ideally be enforced at `apply` time with an admission web-hook or with openapi validation rules. Not after it's been successfully applied.

..a short possible workaround for now; use `api.watch::<serde_json::Value>` or something else dynamic to bypass it.

**Comment by praveenperera** [comment]
My use case it that I will let end users upload CR's. I will have validations in place, but the problem is that they could `apply` the CR with validation disabled. Now with validations being required for CRDs in `apiextensions.k8s.io/v`, 

I guess this is a pretty small edge case that maybe I shouldn't worry about.

I found that, this sort of works. If I delete the offending CR, this will continue to receive new events. 

I guess I could run some code delete the CR if it improperly typed.

```rust
    let mut inform = Informer::new(cert_issuers.clone());

    loop {
        match poll_events(&inform).await {
            Ok(event) => {
                handle(event).await;
            }
            e => {
                let cert_issuers: Api<CertIssuer> = Api::all(client.clone());
                inform = Informer::new(cert_issuers);
            }
        }
    }
```

I'll think about this more. Maybe I can find a way to delete any invalid CRs right away. Or is it possible to not save the CR at all if validations are disabled?

Another thing I was looking at is it possible to serialize the `spec` separately from the other fields (`apiVersion`, `kind` and `metadata`). Because I think this problem could only happen in the `spec` field. Since mistakes in other fields will not get applied even with validations turned off. Then we could return the `spec` field as a Result but still update the `version` in `metadata`

**Comment by teozkr** [comment]
> Another thing I was looking at is it possible to serialize the spec separately from the other fields (apiVersion, kind and metadata). Because I think this problem could only happen in the spec field. Since mistakes in other fields will not get applied even with validations turned off. Then we could return the spec field as a Result but still update the version in metadata

Sadly not, the CRD can customize the whole resource, not just the `spec`.

> Even with --validate=false k8s won't allow the user to create an invalid CR

Yeah, `--validate` only controls kubectl's client-side validation.

That said, there are still ways to mess it up for cluster administrators, like modifying the CRD to allow the invalid state.

**Comment by praveenperera** [comment]
> Sadly not, the CRD can customize the whole resource, not just the spec.

I did not know that.

> That said, there are still ways to mess it up for cluster administrators, like modifying the CRD to allow the invalid state.

I did not know that either. 

So basically for someone making a controller that being used by end users (like the one trying to make now), this might not be a rare situation?  For internal apps you can control what people do. But for anything you're making where the end users can upload their own CRDs and CR YAMLs we should be able to handle errors in the YAMLs.

If this is more of a possibility would it make sense to change how `WatchEvent` works? @clux ?

Any ideas for some good work arounds? Thanks

**Comment by clux** [comment]
It is possible that we could do something here, but I'm a bit confused of why you are in a situation where end users can upload CRDs, but you can't solve it with openapi validation logic on the crd, a small validating admission controller, or an OPA policy.  With that in place they wouldn't be able to apply invalid yaml. Like, where would you delineate type failures without that? Are all controllers going to check all properties? This feels like it shouldn't be the scope of a controller.

If you really want to allow untyped yaml at the controller level, my gut feel is that you need to make an `Informer<CrdObjWithDynamicSpec>` where `CrdObjWithDynamicSpec.spec` is something like `serde_json::Value` and deal with the consequences of that. Or alternatively put `#[serde(default)]` and `Option` around everything.

**Comment by praveenperera** [comment]
> where end users can upload CRDs, but you can't solve it with openapi validation logic on the crd

I'm working on a open source controller, so I'm trying to think through the edge cases, and like @teozkr said above: https://github.com/clux/kube-rs/issues/265#issuecomment-659070574, the user could edit the CRD. (Again, I don't l know why they would). 

I think that this edge case is rare enough that I'm happy with the solution I have above.

> small validating admission controller, or an OPA policy. 

I'll look into these, thanks.

>  #[serde(default)] and Option
This is also a good option.

Should I close this issue?

**Comment by clux** [comment]
Note that if you have an admission controller to do validation, no matter the form: a manually written one / one generated from OPA / the built in k8s one from the openapi schema, the users would NOT be able to `kubectl edit myfooinstance` if it failed myfoocrd's validation.

I believe Theo was cautioning against administrators that could be malicious about the crd (the cluster level resource) and remove the schemas and hence the validation. And yeah, you wouldn't be able to secure around that, but users should not be in a position to do that.

**Comment by praveenperera** [comment]
> Note that if you have an admission controller to do validation, no matter the form: a manually written one / one generated from OPA / the built in k8s one from the openapi schema, the users would NOT be able to kubectl edit myfooinstance to something that fails myfoocrd's validation.

Ok that's  what I was thinking. That is good news. They would really have to go out of their way to break it. 

Since I am using the `apiextensions.k8s.io/v1` where validations are required, they couldn't even just delete the validations. 

They would have to change it to something that breaks. Not something that could happen accidentally.

I'm going to close this issue. Thanks for your help.
