### ISSUE TITLE
Deprecate kube::runtime

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#281]
Replaced by `kube_runtime` crate.

**Comment by clux** [comment]
Yeah, go for it.

Was waiting a bit until I felt confident in the a crate split solution first. From last comment in #204 it feels like we should have either 2 crates (kube (incl runtime) + derive) or 5 crates (1 master exporter crate + config/client + derive + runtime).

If we go for the former, then kube-runtime should replace the current one on the same export path. I guess in either case, a deprecation warning is needed.

**Comment by teozkr** [comment]
Yeah.. either case, any users of the current `kube::runtime` are going to have some migration work in front of them soon.
