### ISSUE TITLE
Drop implicit kind->resource conversion

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#284]
Motivated by #14, but the current behaviour mostly works by accident anyway.

- [ ] Add `RESOURCE_NAME` `const` to `k8s_openapi::Resource` (and add it to their generated object types)
- [ ] Replace `kube::Resource::kind` with `resource_name`
- [ ] Generate `RESOURCE_NAME` from the `CustomResource` deriver
- [ ] Drop `inflector` runtime dependency

**Comment by clux** [comment]
Totally! If it's possible to grab the actual values without relying on pluralization then that would be great. I just assumed the information was not available in the openapi spec by looking at the underlying types; e.g. [Pod](https://github.com/kubernetes/api/blob/e4973e079a1129e83001d8368911eec19d9231fa/core/v1/types.go#L3665-L3686) and introduced the dep in a bit of a hurry.

Wonder how k8s-openapi does this.

**Comment by teozkr** [comment]
You can get the mapping at runtime from the `APIResourceList` endpoints, which seems to be what `kubectl` is doing.

![image](https://user-images.githubusercontent.com/649832/88275592-e761b380-ccdd-11ea-82fb-5b36f10d4caa.png)

Of course, that isn't great for our use-case (wouldn't want to need a running K8s cluster to be able to compile `k8s_openapi`.. :P). Haven't looked through the OpenAPI stuff yet to see whether anything similar is available there.

**Comment by teozkr** [comment]
Looks like the OpenAPI does not include the resource name. On the other hand, I don't think it would be *too* bad to use a heurestic like "find the last path item of the list endpoint`.

**Comment by clux** [comment]
Found another case of our implicit naming not working today when doing #305. `CustomResource` assumes PascalCase + singular kinds, but even kubernetes fails to adhere to this: `APIService`, `CSINode`, `NodeMetrics`, `Endpoints` (as well as numerous CRDs that do not have enforcement ([details](https://github.com/clux/kube-rs/pull/305/commits/276a6b57cfcaf4fe0a33315413da7c96332f4108)).

Ended up removing case/plural pedantry on the dynamic api to a mere debug check. Which is fine, dynamically created resources work if we aren't being strict. But THIS issue means that some of the objects noted in that PR **might not work** with `Api`. Thankfully, only found `Endpoints` (badly pluralised) and `APIResource`/`APIService` (bad pascal) as **NATIVE** failure cases when listing all available resource types (though all of istio's crds were also in violation..) with the new `dynamic_api` example.

Not even sure excess pluralisation in `Endpoints` is an actual failure case either. [`to_plural` should be idempotent](https://docs.rs/Inflector/0.11.4/inflector/string/pluralize/fn.to_plural.html).

Can at least confirm that the required data is there on the api for all cases (albeit awkwardly split between two api calls). Hopefully there's a way we can get the data in the trait in `k8s-openapi` without using any api though. It's not like it's generated from a live cluster, and Arnav is creating the urls with plural somehow, the data must be there.

**Comment by clux** [comment]
There's no easy way of getting the plural as it stands. It happens to be in the urls of the schemas as noted in https://github.com/Arnavion/k8s-openapi/issues/73#issuecomment-671570768. If the k8s-openapi issue resolves, we can progress here, otherwise marking as awaiting upstream work.

**Comment by clux** [comment]
This is less of an issue now that we maintain a pluralisation fn that handles the few non-conformant cases.

All other entry ways no longer need to do this implicitly.

- api-discovery will automatically deduce the plural
- kube-derive optionally allow `#[kube(plural = "fooz")]`

**Comment by MikailBag** [comment]
I've sent https://github.com/Arnavion/k8s-openapi/pull/88 to add resource name to the `k8s-openapi::Resource` trait
