### ISSUE TITLE
Status Of Project

### ISSUE THREAD

**Issue by sstubbs** [clux/kube-rs#288]
Hi,

I have used this library in the past for testing purposes. I would like to now build an operator that's ready for production but I am wondering how stable this project is and how many more breaking changes there will be until there is a stable release. If not I will have to use one of the go options but I prefer to use rust if possible.

**Comment by clux** [comment]
There will almost certainly be __some__ more breaking changes. It's hard to estimate. We hope that we're starting to stabilise, but the last release was pretty major. Expecting a certain amount of fallout.

**Comment by clux** [comment]
That said, changes will be documented in `CHANGELOG`, and you can pin your versions as appropriate.

**Comment by teozkr** [comment]
The API isn't stable yet (we're not 1.0!), but the basic ideas are mostly in place, especially for the API client (`kube`, as opposed to `kube_runtime`).

As @clux mentioned, `0.36.0` was a pretty big and breaking release. That said, I just upgraded an internal project from `0.28.1` to `0.37.0` yesterday in an hour or so. Pretty much all of the changes were either `sed`able renames (such as `APIClient` -> `Client`) or deleting a bunch of code (dropping our custom internal controller runtime in favour of `kube_runtime`).

**Comment by teozkr** [comment]
That said, it's a good discussion to raise. API breakage is one thing, but #286 shows that it might be worth starting to let releases bake for a bit longer.

**Comment by sstubbs** [comment]
ok thanks I think I will use this anyway as I'm a big fan of rust and this library and just not upgrade as frequently as I generally do.

**Comment by clux** [comment]
Awesome. I'll close this for now. We'll revisit stability guarantees and actually define what this entails once 1.0.0 is right on the horizon.
