### ISSUE TITLE
[Question] Controller reconcile function not called when custom resource is deleted?

### ISSUE THREAD

**Issue by praveenperera** [clux/kube-rs#290]
```rust
    Controller::new(cert_issuers.clone(), ListParams::default())
        .owns(certs, ListParams::default())
        .run(reconcile, error_policy, Context::new(Data { client }))
        .for_each(|res| async move {
            match res {
                Ok(o) => info!("reconciled {:?}", o),
                Err(e) => warn!("reconcile failed: {}", e),
            }
        })
        .await;
```

Here cert_issuers is my custom resource. It manages certs.

Reconcile is called when I add the custom resource, or when I change it. But it's not called when I delete the (cert_issuer) custom resource.

Is this how the Controller is supposed to work?

**Comment by clux** [comment]
Because you are not guaranteed to intercept DELETE events (controller downtime, network etc), and you are managing third party resources: you must put a `finalizer` on your CRD to ensure you are guaranteed to clean up.

What happens then is your controller will get a MODIFIED events (on kubectl delete) where the `metadata.deletion_timestamp` is set. You can then clear up the object's third party dependencies, and remove your `finalizer` from the `finalizers` list (causing delete to continue).

**Comment by praveenperera** [comment]
Thanks I was going to do something like this

```rust
    let controller_task = task::spawn(async {
        Controller::new(cert_issuers, ListParams::default().include_uninitialized())
            .owns(certs, ListParams::default())
            .run(reconcile, error_policy, Context::new(Data { client }))
            .for_each(|res| async move {
                match res {
                    Ok(o) => info!("reconciled {:?}", o),
                    Err(e) => warn!("reconcile failed: {}", e),
                }
            })
            .await;
    });

    let watcher_task = task::spawn(async {
        let watcher = watcher(cert_issuers2, ListParams::default());
        let _ = watcher
            .try_for_each(|event| async move {
                match event {
                    watcher::Event::Deleted(event) => handle_delete(event),
                    _event => (),
                }
                Ok(())
            })
            .await;
    });

    let _ = futures::join!(controller_task, watcher_task);
```

And whenever `reconcile` is called also check to see if any CRs were deleted since last time (just in case I missed some DELETE events).

But I think the finalizer route would be better. Thanks!
