### ISSUE TITLE
PatchParams::default_apply().field_manager is always `kube`

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#300]
`$CARGO_PKG_NAME` is the name of the library crate, not the "root" application crate.

**Comment by clux** [comment]
We could change `default_apply` signature to return `Result<Self>` and infer a reasonable name from `std::env::current_exe()` and passing it through `Path::file_name`?

Can't think of a better solution atm :(

**Comment by teozkr** [comment]
IMO, just take the name as a parameter. `current_exe` is way too gotcha-prone for this to be safe (what about running multiple controllers in the same executable? cohabitating a controller with some other direct manipulation? symlinks?). Besides, it's not like `kube-derive` is trying to infer the API group from the crate version number or the primary author's email address.

**Comment by clux** [comment]
Yeah, that's a fair argument. I was only hiding the value because I felt it didn't really matter unless you were in a case with multiple owning controllers, but it's at least less gotcha-y to be explicit.
