### ISSUE TITLE
the trait `k8s_openapi::Metadata` is not implemented for `helmreleasespec::models::HelmReleaseSpec`

### ISSUE THREAD

**Issue by PeterGrace** [clux/kube-rs#303]
Hello again!

I am trying to extend the multi watcher example by watching a custom resource definition.  I  used the openapiv3 schema to try to generate the proper structs to realize the CRD I'm trying to import (HelmRelease, a part of the FluxCD project).  When I try to derive CustomResource on the struct, however, I get the following error:

```
error[E0277]: the trait bound `helmreleasespec::models::HelmReleaseSpec: k8s_openapi::Resource` is not satisfied
  --> src\main.rs:33:48
   |
33 |     let cl_helmrelease: Api<HelmReleaseSpec> = Api::all(client).clone();
   |                                                ^^^^^^^^ the trait `k8s_openapi::Resource` is not implemented for `helmreleasespec::models::HelmReleaseSpec`
   |
   = note: required by `kube::Api::<K>::all`
```
The source for my project is up-to-date in this repo:  https://github.com/PeterGrace/herald  -- I would love any pointers that might shed some light on this issue.  If it turns out I'm doing this way too hard and there's an easier way to look for fields inside of a defined custom resource beyond implementing-the-whole-thing, I'd love to hear about it!

My eventual goal is to write an app that can use a template engine to pull fields from resources and notify something via webhook.  e.g. if the image tag of a Pod changed, or a value in a HashMap changed, etc.

**Comment by teozkr** [comment]
`CustomResource` automatically creates a new `HelmRelease` struct to correspond with your `HelmReleaseSpec` (which only covers the `spec` part of the CRD). `k8s_openapi::Resource` is implemented for your CRD struct (`HelmRelease`), not for your spec struct (`HelmReleaseSpec`).

This can be a bit confusing and should probably be documented more clearly, but as a workaround you can run `cargo doc --document-private-items` to build a rustdoc site that shows the generated structs and impls, and their contents.

**Comment by PeterGrace** [comment]
Thank you very much -- I had no idea that that was the case, thought its a possibility I just glossed over it in the docs without grokking what it meant.
