### ISSUE TITLE
Expose authn method in `kube::Config`

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#322]
Some APIs (such as Istio's control plane) use K8s bearer tokens for their own ends. You can access it through `kube::config::Kubeconfig`, but that:

1. Doesn't resolve the current context
2. Doesn't support in-cluster configs

**Comment by clux** [comment]
I'm a bit confused about this one. Do we need to expose some of the `load_auth_header` mechanics, you think?

Is this used to actually create a `Client`? Or if it is, could we create another way to create a `ConfigLoader`?

**Comment by teozkr** [comment]
In Istio's case, you need to reuse the K8s bearer token to authenticate to their API. It doesn't involve a `kube::Client` unless you also want to use the K8s API directly.

**Comment by teozkr** [comment]
To clarify.. Istio is *configured* via K8s CRDs, but also has a separate gRPC runtime APIs (for issuing certs and viewing the cluster state).

**Comment by clux** [comment]
Released in 0.43.0
