### ISSUE TITLE
is ConnectionReset worth an error!()?

### ISSUE THREAD

**Issue by dimbleby** [clux/kube-rs#335]
What got me looking at the timeouts per #334 was that when nothing else is going on we are seeing logs like this:
```
{"msg":"err poll: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" }) } - request or response body error: error reading a body from connection: Connection
reset by peer (os error 104)","level":"ERRO","ts":"2020-11-05T04:17:16.984142437+00:00"}
{"msg":"err poll: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" }) } - request or response body error: error reading a body from connection: Connection
reset by peer (os error 104)","level":"ERRO","ts":"2020-11-05T04:21:42.316377599+00:00"}
{"msg":"err poll: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" }) } - request or response body error: error reading a body from connection: Connection
reset by peer (os error 104)","level":"ERRO","ts":"2020-11-05T04:26:07.282497227+00:00"}
{"msg":"err poll: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" }) } - request or response body error: error reading a body from connection: Connection
reset by peer (os error 104)","level":"ERRO","ts":"2020-11-05T04:30:31.788507495+00:00"}
{"msg":"err poll: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" }) } - request or response body error: error reading a body from connection: Connection
reset by peer (os error 104)","level":"ERRO","ts":"2020-11-05T04:34:56.915212708+00:00"}
{"msg":"err poll: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" }) } - request or response body error: error reading a body from connection: Connection
reset by peer (os error 104)","level":"ERRO","ts":"2020-11-05T04:39:22.701149376+00:00"}
{"msg":"err poll: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" }) } - request or response body error: error reading a body from connection: Connection
reset by peer (os error 104)","level":"ERRO","ts":"2020-11-05T04:53:37.627088911+00:00"}
```

which seem mostly to be happening at a puzzling 265s interval.

I am guessing that this is somehow derived from one of the timeouts we provide, but haven't found how exactly.

Anyway, the extreme regularity of this log suggests that it is just the server timing things out, in which case logging an `error!()` is a bit much.

If so I think that this should be treated in the same way as [timeouts](https://github.com/clux/kube-rs/blob/3c230e08a6dd239cbfeba0ad060305d62d1fe31b/kube/src/client/mod.rs#L246-L247).  Though perhaps even `warn!()` is a bit strong for something that's totally expected, maybe `info!()` is better?

I'm not sure that I have fully understood how timeouts are interacting to produce the above results; but if you think I'm on the right track I could probably manage a merge request to treat "Connection reset by peer" less aggressively.

**Comment by clux** [comment]
Maybe a `warn!` here would be better, but it does represent a failure. It's not great if it's happening that frequently, I'd perhaps try to drop your timeouts down a little bit and figure out why they are happening. I've personally never seen consistently reset connections in the below 300s timeout range.

**Comment by teozkr** [comment]
Have you enabled bookmarks in your `ListParams`? Are you using a load balancer in front of your API server with an idle timeout? If so, make sure that your bookmark interval is lower than the idle timeout..

**Comment by dimbleby** [comment]
We had not enabled bookmarks.

We are using Azure AKS clusters: I don't find a clear discussion of whether that inserts its own timeouts, but maybe.

I will experiment with using bookmarks and shorter client timeouts, thanks for the suggestion.

**Comment by clux** [comment]
This should not happen with bookmarks, and the client has been refactored significantly since this issue. I.e. log messages are no longer what this issue says, so all this combined means it's probably worth closing this issue for now.

Of course, if you are experiencing strange resets still, __and__ you are using bookmarks, please open another issue.
