### ISSUE TITLE
Using Reflector with Controller

### ISSUE THREAD

**Issue by cswinter** [clux/kube-rs#337]
I'm new to both custom controllers and kube-rs so apologies if this is a noob question. I'm trying to write a controller for a custom resource that will spawn pods similar to a `Job`. I'm using the [controller-rs](https://github.com/clux/controller-rs) project as my starting point and have it set up to trigger reconcile on any changes to my custom resource or relevant pods. To decide what actions to take, `reconcile` ought to query the latest state of the custom resource and any associated pods. I think I'm meant to use a `Reflector` to maintain a cache of the latest known state of all relevant custom resources/pods to make these queries efficient.

The first part I'm struggling with is how to maintain the stores. I can create a reflector as in [deployment_reflector.rs](https://github.com/clux/kube-rs/blob/master/examples/deployment_reflector.rs), but presumably to keep updating the cache I need to keep awaiting new events. My first instinct is to spawn a tokio task that will keep running the watcher loop, but this doesn't seem to work because the reflector stream is not `Send`.

The second part I'm not sure how to achieve is waiting for all the stores to catch up with the initial flurry of events before allowing the controller to start running and potentially acting on very incomplete state. Ideally, I would also like to tie the watcher loop into the controller somehow in a way that to ensures that `reconcile` will not process any events that have not yet been applied to the stores.

**Comment by teozkr** [comment]
> but this doesn't seem to work because the reflector stream is not Send.

It.. should be, that sounds like a bug.

> I can create a reflector as in deployment_reflector.rs, but presumably to keep updating the cache I need to keep awaiting new events. My first instinct is to spawn a tokio task that will keep running the watcher loop

The correct thing to do here *should* be to use [`Controller::owns`](https://docs.rs/kube-runtime/0.43.0/kube_runtime/controller/struct.Controller.html#method.owns) or `Controller::watches`, but neither of those actually support feeding a `Reflector` at the moment.. :/

**Comment by clux** [comment]
The `Send` part is probably because the reflector returns a watch stream, which is not `Send` by default, unless it's put in a `BoxedStream`. But there's not actually a need require this, you could just put a `for_each` on the stream:

```rust
    let rf = reflector(store, watcher(myapi, lp));
    let drainer = try_flatten_touched(rf)
        .filter_map(|x| async move { std::result::Result::ok(x) })
        .for_each(|o| {
            debug!("Touched {:?}", Meta::name(&o));
            futures::future::ready(())
        });
```

and await the drainer future at the end in a `select!` with whatever other runtime futures you may have.

As for feeding the store back into the reconciliation loop, I would try to put the store on your Context struct.

**Comment by cswinter** [comment]
Thanks for the detailed explanations, this makes sense now!

> The correct thing to do here should be to use Controller::owns or Controller::watches, but neither of those actually support feeding a Reflector at the moment.. :/

I'm just gonna be prototyping things for a while so not concerned about getting it as correct as possible, but good to know this might be an option in the future.
