### ISSUE TITLE
websocket connections can panic based on connection errors

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#369]
https://github.com/clux/kube-rs/blob/e4d999b361ae59c6755205658bf4c8638595c616/kube/src/client/mod.rs#L156-L160

For example, async-tungstenite in rustls mode will convert TLS errors into `ws2::Error::Io` (since `ws2::Error::Tls` is only available in native TLS mode), which would cause a panic.

https://github.com/sdroege/async-tungstenite/blob/33e3722ab0931551128887e6ed6b2af78498427a/src/tokio/rustls.rs#L44-L49

I'd also assume that basic stuff like "no route to host" or "connection refused" would be IO errors (and thus also panic).

I'm also a bit wary of the general policy of a catch-all panic case, which would bite us hard if they ever decide to split up any error cases (for example).

**Comment by clux** [comment]
Ah, yes. That probably deserves some kind of `ConnectionError` type.

**Comment by kazk** [comment]
> since `ws2::Error::Tls` is only available in native TLS mode

Ugh, I guess I never compiled with `rustls` after adding those. Thanks for catching and fixing it.

> I'm also a bit wary of the general policy of a catch-all panic case

Agreed. I'll improve it. I wish they had separate errors that's more descriptive.
