### ISSUE TITLE
Test ws features on Circle CI

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#378]
https://github.com/snapview/tokio-tungstenite/pull/142 means that Tungstenite (the websocket client) is still using Tokio 0.2, which may crash at runtime since it can't find a valid Tokio 0.2 context (since it is distinct from a Tokio 1.0 context).

I missed this in the initial upgrade because most of that work was done before #360 was merged.

In the meantime, use [`tokio-compat-02`](https://docs.rs/tokio-compat-02/0.2.0/tokio_compat_02/) if you need any websocket features.

**Comment by kazk** [comment]
We don't use `tokio-tungstenite` (using `async-tungstenite` with `tokio-runtime` mainly because that supports `rustls`) and `tungstenite` itself doesn't depend on `tokio`.

`ws` example is working locally for me on `master`. But we should get some tests running on Circle CI.

**Comment by kazk** [comment]
We do have `bytes` v0.5 from multiple crates (`http`, `tungstenite`, `k8s-openapi` (updated but unreleased)) though.

**Comment by clux** [comment]
Examples are running with and without the `ws` feature since #394, and `tokio` is all at >1 in `cargo tree`, so closing this for now.
CI is at least testing it, although it is struggling a bit under my free circleci plan.
