### ISSUE TITLE
How to do something like "kubectl cp"?

### ISSUE THREAD

**Issue by acim** [clux/kube-rs#381]
I would like to make a utility to access files in a pod in order to make a backup, for example. Is this library capable of doing so and how? Thank you.

**Comment by clux** [comment]
Judging from a similar issue on another client: https://github.com/fabric8io/kubernetes-client/issues/868 - it seems like it uses the newly added pods/exec feature (#360), so looks like it __should just work__™.

Will keep this open until we have an example.
