### ISSUE TITLE
Best way to check that a deployment is ready?

### ISSUE THREAD

**Issue by GSGerritsen** [clux/kube-rs#391]
If anyone has a snippet that shows how to use the `while let Some(event) = rfa.try_next().await? { ... }`  reflector stream that can signal when a deployment is fully up and ready, that would be super helpful.

I'm able to stream the names of events but it's tough to use that to signal that a deployment is up, especially in the case where pods are restarting. 

Ideally I could do something like this: `let deployment_ready = wait_for_deployment("deployment-name", 10).await?;` with the second arg being a timeout.

**Comment by clux** [comment]
If it's for dealing with rolling upgrades, then there's a tracking module in `shipcat` which deals with various [rollout cases](https://github.com/babylonhealth/shipcat/blob/master/shipcat_cli/src/track.rs#L317). The key thing is finding the corresponding replicaset by hash and then querying that.

**Comment by teozkr** [comment]
Depends on how you define "up and ready". At least one replica is updated and available? All replicas are updated and available? No more outdated replicas are available?

**Comment by clux** [comment]
Going to close this one.

The data is generally all there on the status object of the Deployment, its associated ReplicaSet (which you can find by template hash), and the ReplicaSet's associated pods. In newer kubernetes versions it might be enough to look at the the `NewReplicaSetAvailable` DeploymentStatus condition as a quick check for if the new rollout is ready to receive traffic.

But for kubernetes questions guidance questions like this, I'd recommend asking in the discord or poking into the official [kubernetes slack](https://slack.k8s.io/).
