### ISSUE TITLE
Question: How do I get `metadata` out of the cache?

### ISSUE THREAD

**Issue by technosophos** [clux/kube-rs#4]
I need to read the labels and annotations on a CRD. Is there a way to get that information out of the cache? It looks like maybe only the `spec` is cached.

https://github.com/clux/kube-rs/blob/master/src/api/reflector.rs#L138

**Comment by clux** [comment]
Yeah, it's been deliberately hidden atm. Not been too sure about it. Might make a better output struct for it.

**Comment by technosophos** [comment]
I was just looking through the new code (I'm still running 0.2). The tuple isn't too bad, but I guess that it sorta becomes an ad hoc struct when more fields get added to it. My particular use case is rather full-featured, since I need access to the status AND access to the labels, as well as to the spec. So I know I might be an outlier of a use case right now.

But I am really excited about your approach. I've done several Go-based controllers, and just don't enjoy writing them. With my early experiment on this library, it feels much better. Rust's type system feels more amenable to the way Kubernetes works (generics, pattern matching, and traits help a lot in that regard).

**Comment by clux** [comment]
Appreciate it.

It does seem like all the watch calls (at least i went through quite a few of them) returns a subset of `.metadata`, `.spec`, and `.status` (status being the generally optional one). It's possible I can force the output into something that has all three, but it also might be better to force the output into a user defined struct so people can do:

```rust
use k8s_openapi::api::apps::v1::{DeploymentSpec, DeploymentStatus};
let r: Reflector<Deployment> = ...
```

rather than

```rust
use k8s_openapi::api::apps::v1::{DeploymentSpec, DeploymentStatus};
let r: Reflector<DeploymentSpec, DeploymentStatus> = ...
```

buncha optionals and mandatory unwraps on the openapi stuff though. I liked just grabbing `.spec` directly (particularly CRDs that often have no need for anything else).

**Comment by clux** [comment]
Have changed the output in ResourceMap to be the internal `Resource<T,U>` type for it, so you can grab the `value.metadata`, `value.spec` and sometimes `value.status`. It's a nicer thing to iterate over anyway, and people are going to need that data. Have only exposed parts of metadata atm, will probably port more from [ObjectMeta](https://docs.rs/k8s-openapi/0.4.0/k8s_openapi/apimachinery/pkg/apis/meta/v1/struct.ObjectMeta.html) with smarter serde attrs for next release.

```toml
kube = { git = "https://github.com/clux/kube-rs", rev = "2624341b8abc7b6cfaa3c9cb31db716db44d10e8" }
```

Thanks for the report, please do raise other annoyances you run into!

**Comment by technosophos** [comment]
Okay. I'm going to try to test this out today or tomorrow. Thank you much!

**Comment by technosophos** [comment]
Just to confirm: I am now successfully working with the metadata section! Thanks.
