### ISSUE TITLE
pr at kubecon 2021?

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#412]
kubecon just announced again, and this time they are going to have a day dedicated to the rust:

https://twitter.com/HeavyPackets/status/1358902608426135559

We [spoke last kubecon](https://www.youtube.com/watch?v=JmwnRcc2m2A) about the `Api` and briefly about the `kube-runtime` library, so not sure there's a lot new for me to talk about (the library has had a lot of improvement to its internals, connections, websockets, hyper, tower, crds, but it's probably not the right audience for internals). Maybe some kind of deep dive or something more practical could make sense?

At any rate, the CFP deadline is next Friday. Does anyone feel there are good things worth talking about to a kubecon audience from our POV?

**Comment by clux** [comment]
had a think this weekend, and can't think of enough good reasons for me to do it, so am probably not going to overload myself.

The only thing that feels sufficiently user-facing to warrant a talk would be CRD generation, and while it's seen a lot of improvement in the past two months, there are still unknowns with movement on issues (structural schemas, enums, k8s-openapi interaction), and it feels too early to talk a lot about it for that. Maybe I'll write a less stressful blogpost instead.
 
Hopefully next year, the controller experience is fleshed out enough that we can do a deep dive - incorporating wisdom from the various struggles people who tried it out early were having - and be in a really good testing place.

**Comment by teozkr** [comment]
Makes sense to me.
