### ISSUE TITLE
GitHub search result for "kubernetes rust"/"kube rust" doesn't include this repo

### ISSUE THREAD

**Issue by kazk** [clux/kube-rs#414]
I noticed this repository is not shown **at all** for some reason.

See <https://github.com/search?q=kubernetes+rust>. Even <https://github.com/search?q=kube+rust> doesn't :( https://github.com/search?q=kube+rs works.

Does anyone know how to fix this?

Maybe make "kubernetes" in description capitalized? Add Rust to description and `rust` to topics?

**Comment by clux** [comment]
ah, that's not good.
I guess github, while it search lets you filter on language, does not hook the language into the main search text :(

I have added rust to the description and the search now works!

**Comment by kazk** [comment]
I guess topic works as well.

![image](https://user-images.githubusercontent.com/639336/107750025-487bc380-6cd0-11eb-94f3-cc564e98cd92.png)
is included in "kubernetes rust".
