### ISSUE TITLE
pod_openapi build error

### ISSUE THREAD

**Issue by anxiousmodernman** [clux/kube-rs#42]
I get this error when running `cargo build --example pod_openapi` after cloning this repo.

![image](https://user-images.githubusercontent.com/396004/59072151-7ff56400-888f-11e9-8d6a-e38822fd7b6f.png)

This is odd, because I can clearly see the implementation in my IDE.

**Comment by clux** [comment]
Ah, that's because the openapi examples (and most other examples that use `Api`) require the build flag: `--features=openapi` at the moment.
