### ISSUE TITLE
Enable GitHub Discussions?

### ISSUE THREAD

**Issue by kazk** [clux/kube-rs#421]
Using GitHub Discussions for questions/ideas will be nice.

See https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository

**Comment by clux** [comment]
We can try it out. It seems like a good idea to try to consolidate some usage questions/ideas. It kind of gets quickly bypassed on discord and we don't really monitor stackoverflow for questions.

**Comment by clux** [comment]
Wrote up a (hopefully) non-threatening intro in #422 :-)
Feel free to tack your names on there.

**Comment by kazk** [comment]
Thanks! I might post a question about `Controller`.

By the way, it's also possible to convert issues with a label into discussions.

![image](https://user-images.githubusercontent.com/639336/107993908-69723c00-6f90-11eb-9423-e3fdc7a66142.png)

I haven't tried, but it looks like it'll convert all issues with that label (and GitHub [can't convert them back at the moment](https://github.com/github/feedback/discussions/2861)), so it's better to add "discussions" label for those we think worth converting (including answered questions) and converting them.

**Comment by clux** [comment]
oh, interesting, yeah, good idea. i'll add that label.
