### ISSUE TITLE
Create a mock Client for testing

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#429]
Create a mockable `Client` that allows us to perform fake `Api` calls, intercept the output, and send fake responses to it.

Why?:

- Allows us (maintainers) to unit test `kube::Api` and `kube_runtime`
- Allows us (maintainers) to unit test Api -> Service interactions (like the proposed default_namespaced in #209)
- Allows users to unit test their abstractions on top of `kube::Api` and `kube_runtime` by faking a few responses

Asked for in #426.

This is something that is theoretically possible through something like [`tower_test`](https://docs.rs/tower-test/0.4.0/tower_test/macro.assert_request_eq.html), but it brings with it complications:

- `Client` would need to take two types of `Service`'s (one of which intercepts calls and allows shoehorning in responses)
- ~~Multiple `Client` types => generic parameter required in `Api` (since it houses the `Client`) - discussed in #406~~
- ~~The latter is a huge breaking change (though not necessarily against it unless it can be avoided)~~
- Actually shoehorning in responses to a MockService [seems hairy based on `tower_test::Mock`](https://docs.rs/tower-test/0.4.0/src/tower_test/mock/mod.rs.html#56-61)

This is a more important (and concrete) want than what is nebulously outlined in #406 - so we probably close that in favour of this testing issue.

---

UPDATE: `Client` takes `Service<http::Request<hyper::Body>>` (#532) so this is easier now.

**Comment by clux** [comment]
One point on the potential breaking change, if we are to do it, we should try our best to ensure the ergonomics of it stay as close to "specify the service generic once, have it be inferred everywhere else" when modifying `Api.`

**Comment by kazk** [comment]
`kube::Service` was added to avoid adding a type parameter to Client. It should be possible to create a mock service (its `new` takes any tower Service as long as request and response type matches) and create a Client with it.

Maybe I missed something? I’m on my phone right now, so I’ll look into it later.

**Comment by clux** [comment]
**If** it's possible to use `kube::Service` directly, then that would be great!
I only did some small experiments that led me to believe that we would have to add a lot to `kube::Service` to be able to support both a mockable mode and a normal mode, but maybe I am wrong.

**Comment by kazk** [comment]
The following works:

```rust
#[cfg(test)]
mod tests {
    use kube::{Api, Client, Service};

    use futures::pin_mut;
    use http::{Request, Response};
    use hyper::Body;
    use k8s_openapi::api::core::v1::Pod;
    use tower_test::mock;

    #[tokio::test]
    async fn test_mock() {
        let (mock_service, handle) = mock::pair::<Request<Body>, Response<Body>>();
        let spawned = tokio::spawn(async move {
            // Receive a request for pod and respond with it
            pin_mut!(handle);
            let (request, send) = handle.next_request().await.expect("service not called");
            assert_eq!(request.method(), http::Method::GET);
            println!("{:?}", request);
            let pod: Pod = serde_json::from_value(serde_json::json!({
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": { "name": "test" },
                "spec": {
                    "containers": [{
                        "name": "test",
                        "image": "test-image"
                    }],
                }
            }))
            .unwrap();
            send.send_response(
                Response::builder()
                    .body(Body::from(serde_json::to_vec(&pod).unwrap()))
                    .unwrap(),
            );
        });

        // `kube::Service` takes `tower::Service` with request/response of `hyper::Body`
        let service = Service::new(mock_service);
        // `kube::Client` takes `kube::Service` to avoid additional type parameter
        let client = Client::new(service);
        let pods: Api<Pod> = Api::namespaced(client, "default");
        // Make a request
        let _pod = pods.get("test").await.unwrap();
        // Asssertions ...
        spawned.await.unwrap();
    }
}
```

I'd like to provide something more convenient, though.

**Comment by clux** [comment]
Ah, that is not bad for out of the box!

I assumed we had to build something on top of our Service, but I had approached it the annoying way of trying to get all our service layers into the mock, which probably isn't that useful for end-users, but somewhat useful for us when unit testing. Not sure if that's worth pursuing. We can test auth at a unit test level within service at the very least - and that's the layer that probably is most test-worthy.

**Comment by kazk** [comment]
Yeah, I'd test layers separately like I did for `AuthLayer`.

> I had approached it the annoying way of trying to get all our service layers into the mock, which probably isn't that useful for end-users, but somewhat useful for us when unit testing.

If you want, you should be able to define a function that returns the default stack, then apply that layer, something like `mock_service.layer(default_stack())` (might need to use `ServiceBuilder`).

**Comment by chroche** [comment]
Thanks, it works!

For what it's worth this is what I came up with. The code is not self-contained (also probably far from optimal), but I guess it may help somebody looking for more examples of the syntax.
```rust
#[tokio::test(flavor="current_thread")]
async fn test_k8s() {

  use std::{fs::File, io::BufReader};
  use http::{Request, Response};
  use hyper::Body;
  use kube::{Client, Service, api::{Api, ListParams, ObjectList}};
  use tower_test::{mock, mock::Handle};
  use k8s_openapi::api::core::v1::{Node, Pod};
  use super::{AsgInstance, eks::{ClientInfo, NodeInfo, PodInfo}};

  async fn mock_k8s(handle: &mut Handle<Request<Body>, Response<Body>>) {

    use kube::api::ListMeta;
    use serde::{Serialize, Deserialize};

    #[derive(Serialize, Deserialize)]
    struct ObjectListDef<T> where T: Clone,
    {
        pub metadata: ListMeta,
        pub items: Vec<T>,
    }

    let (request, send) = handle.next_request().await.expect("Service not called");

    let body = match request.uri().to_string().as_str() {
      "/api/v1/nodes?" => {
        let file = File::open("sample/nodes.json").unwrap();
        let reader = BufReader::new(file);
        let nodes: ObjectListDef<Node> = serde_json::from_reader(reader).unwrap();
        serde_json::to_vec(&nodes).unwrap()
      },
      "/api/v1/namespaces/kube-system/pods?" => {
        let file = File::open("sample/pods.json").unwrap();
        let reader = BufReader::new(file);
        let pods: ObjectListDef<Pod> = serde_json::from_reader(reader).unwrap();
        serde_json::to_vec(&pods).unwrap()
      },
      _ => panic!("Unexpected API request {:?}", request),
    };

    send.send_response(
      Response::builder()
        .body(Body::from(body))
        .unwrap());
  }

  let (mock_service, mut handle) = mock::pair::<Request<Body>, Response<Body>>();
  let service = Service::new(mock_service);
  let client = Client::new(service);

  let c = client.clone();
  let h = mock_k8s(&mut handle);
  let (result, _) = futures::join!(c.get_count(), h);
  let count = result.unwrap();

  assert_eq!(count, 1);

  let c = client.clone();
  let h = mock_k8s(&mut handle);
  let inst = AsgInstance{ id: String::from("i-06a31794b0771a1a9"), zone: String::from("us-east-1a") };
  let (result, _) = futures::join!(c.get_node(&inst), h);
  let node = result.unwrap();

  assert_eq!(node.unwrap().name(), "ip-10-169-187-100.ec2.internal");

  let c = client.clone();
  let h = mock_k8s(&mut handle);
  let n = Api::namespaced(c, "kube-system");
  let p = ListParams::default();
  let (result, _) = futures::join!(n.list(&p), h);
  let pods: ObjectList<Pod> = result.unwrap();
  let pod = pods.iter().next().unwrap().to_owned();

  assert_eq!(pod.name(), "aws-node-g8m5d");
  assert_eq!(pod.owner(), Some("DaemonSet"));
  assert_eq!(pod.phase(), Some("Running"));
  assert_eq!(pod.can_evict(), false);
}
```

**Comment by kazk** [comment]
Using `tower_test::mock::Handle` (like an [example provided by a user](https://github.com/clux/kube-rs/discussions/426#discussioncomment-423595)):

```rust
async fn mock_get_pod(handle: &mut Handle<Request<Body>, Response<Body>>) {
    let (request, send) = handle.next_request().await.expect("Service not called");

    let body = match (request.method().as_str(), request.uri().to_string().as_str()) {
        ("GET", "/api/v1/namespaces/default/pods/test") => {
            // Can also use recorded resources by reading from a file.
            // Or create entire mock from some file mapping routes to resources.
            let pod: Pod = serde_json::from_value(serde_json::json!({
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": {
                    "name": "test",
                    "annotations": { "kube-rs": "test" },
                },
                "spec": {
                    "containers": [{ "name": "test", "image": "test-image" }],
                }
            }))
            .unwrap();
            serde_json::to_vec(&pod).unwrap()
        }
        _ => panic!("Unexpected API request {:?}", request),
    };

    send.send_response(Response::builder().body(Body::from(body)).unwrap());
}
```

Used like:
```rust
#[tokio::test]
async fn test_mock_handle() {
    let (mock_service, mut handle) = mock::pair::<Request<Body>, Response<Body>>();
    let spawned = tokio::spawn(async move {
        mock_get_pod(&mut handle).await;
    });
    let pods: Api<Pod> = Api::default_namespaced(Client::new(mock_service));
    let pod = pods.get("test").await.unwrap();
    assert_eq!(pod.annotations().get("kube-rs").unwrap(), "test");
    spawned.await.unwrap();
}
```

Now with `kube::Service` removed, it's pretty straightforward. We can add some helpers and come up with conventions to make this more convenient, but it's usable already.

**Comment by kazk** [comment]
@clux I think we don't need anything else on `Client` now that it can use mock Service directly. I'll continue playing with `tower_test` and see if I find anything better. Maybe this can be closed, and new issues can be opened for adding test helpers (not sure what yet).

**Comment by clux** [comment]
Yeah, I agree. The situation is pretty good now, and improvement is likely to come from helper functions.

Side note; It feels really hard to present a nice interface for testing controllers well. So many potential flows to keep track of, even the basic test case would be something like: 1. watchevent input -> 2. reconcile start -> 3. reconcile asks something of the api 4. api mock returns canned response, 5. reconcile decides on action, 6. we verify final request.

But yeah, let's close. The core issue (and many other things __this__ issue was originally concerned with) are dealt with :+1:

**Comment by kazk** [comment]
Yeah, this will be useful for small unit tests, but I don't think it's realistic to test controller's complex behavior like this. It should be possible to make stateful mocks (like `POST` and then `GET`, or change response after some condition), but it'll be painful to manage for complex scenarios. 

For that, I think we should add a test helper to start a cluster for each test (#382), and some test macros for convenience.
