### ISSUE TITLE
tracing instrumentation

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#457]
Following on from #423 and a tracing deep dive. Here are a few goals I feel our tracing instrumentation should follow:

1. [x] `kube` should allow users to see when and how long `Api` operations take by whitelisting `kube=trace` in an `EnvFilter`, thus showing users the generated spans around all `Api` methods - see #455 
2.  [x] `controller-rs` + examples should hook into this, and show a good default way to generating root spans in a `reconcile` so that we can trace each reconcile (the part of the user code that most controller writers care about) - see https://github.com/clux/controller-rs/pull/10 (each `reconcile` gets a trace id)
3. [ ] `kube-runtime` should additionally help users see the lifecycle of an event as it is received, until it is passed into `reconcile`, thus giving users a way to [finding out what triggered a reconciliation](https://github.com/clux/kube-rs/discussions/423) by opting in to an `EnvFilter` whitelisting `kube-runtime=trace`

Those are the main use cases I can think of that I think would provide the most immediate value, if there are others, please share.

As a bonus: here is a screenshot of instrumentation of 1. and 2. which i PoCd earlier in the two prs:
![Screenshot from 2021-03-09 20-40-51](https://user-images.githubusercontent.com/134092/110535278-f8015580-8117-11eb-9e16-50d9e22aff0d.png)

Only two spans (and a missing service name, plz ignore), because this `reconcile` only made one Api call as it's a demo, but you have timings, associated logs, context (from the newly added Debug impls), and the possibility for users to extend arbitrarily with their own instrumented business logic. This is just a nice default for kube and a controller (if you don't care about point 3) IMO.

**Comment by clux** [comment]
one potential difficulty with instrumentation of `kube-runtime` is that one received event might lead to more than one reconcile if we are not careful with where we place the root span.

If we place the root span where we receive the event, it could be very difficult to close that span because everything kind of just spins around in kube-runtime's stream machinery. I have not had a go at this, and it's not at the top of my list, so anyone wanting to look at it, go for it. This is just a bit of cautionary speculation.

**Comment by clux** [comment]
Want to do some more work here in kube. Not completely satisfied with the way the spans display the Debug impl of all the ListParams like it's crucial information.

I think rather than  instrumenting every `Api::` method, we should move instrumentation to the Logging layer, and do a more diligent tracing setup that conforms to [otel semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md)

**Comment by kazk** [comment]
> we should move instrumentation to the Logging layer

FYI, `tower-http` recently merged `TraceLayer` that's fully customizable (see https://github.com/tower-rs/tower-http/pull/77). They're working on metrics too (https://github.com/tower-rs/tower-http/pull/86).

**Comment by clux** [comment]
Opening this issue up a bit more now. The `api` is pretty well instrumented now via the [`TraceLayer` in the `Service` stack](https://github.com/clux/kube-rs/blob/0f802b59f0c1db6eb6df72b8c35a4429b12068c2/kube/src/client/mod.rs#L457-L508).

But the more difficult part of how to instrument the runtime. Particularly with the goal to [figure out what caused the reconciliation](https://github.com/clux/kube-rs/discussions/423). This feels a lot more uncertain and I don't see a clean way to do this yet with the way the stream machinery is set up.

It's possible we need to inject origin objects into the scheduler for the runtime (or something to that effect), and do simpler spans whenever the scheduler decides it's time to reconcile an object.

Ideas welcome.
