### ISSUE TITLE
Doesn't support CRD which has a special value for kind, plural, singular and etc

### ISSUE THREAD

**Issue by iming0319** [clux/kube-rs#458]
The CRD usage goes wrong when the spec.name.kind is not a single word.
For example, a part of NetworkAttachmentDefinition spec is
==== START ===
spec:
  conversion:
    strategy: None
  group: k8s.cni.cncf.io
  names:
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    plural: network-attachment-definitions
    shortNames:
    - net-attach-def
    singular: network-attachment-definition
==== OVER ===
You can see the plural is not low-case "NetworkAttachmentDefinition".
Please provide a solution for this case.
Thanks a lot.

**Comment by clux** [comment]
Looks like this attr is not documented at the moment, but you can use `#[kube(plural = "network-attachment-definitions")]`.

**Comment by clux** [comment]
Oh, wait you need a non-standard singular as well. Yeah, we need a flag for that.

**Comment by clux** [comment]
Someone else feel free to tackle this, I am busy on other things this week.
