### ISSUE TITLE
DynamicResource should be replaced by DynamicObject

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#464]
At the moment the api-discovery system in the client gives you `DynamicResource`s in master.
However, to be turned into an `Api`, it goes thorugh:

```
pub fn try_into_api<K: Meta>(self, client: Client) -> Result<Api<K>>
```

i.e. it requires you having the type `K` already implementing `Meta`.
If we instead do this type of impls on `DynamicResource`, and construct the GVK behind the seems, it seems plausible to me that users can get an `Api` with a `GVK` family.

What do you think @MikailBag ?

**Comment by clux** [comment]
Acceptance goals: `dynamic_api` example should be extendable so that we can add a `dynapi.list()` and print names of everything.
This would give us functionality like `kubectl get all --all`.

**Comment by MikailBag** [comment]
> it requires you having the type K already implementing Meta.

I think that `kube::Api::DynamicObject` should work as a K.
I've sent #466 to update dynamic_api example.
