### ISSUE TITLE
Do not guess resource endpoints

### ISSUE THREAD

**Issue by MikailBag** [clux/kube-rs#467]
Currently `Resource` (which is the only entity that is actually working with Kubernetes URLs) only known resource kind (such as "Pod"). However, URLs contain resource name instead (e.g. "pods" or "statefulsets"). `Resource` [uses](https://github.com/clux/kube-rs/blob/0720a3d6e571f39607890f37d368a98cb2a2f721/kube/src/api/resource.rs#L106) `inflector` crate to pluralize the kind and assumes that is it valid resource name. Although it works for most of resources, this means that is impossible to use `Client` with resources that do not follow this scheme (no matter are you using typed `Api<k8s_openapi::Foo>` or untyped `Api<DynamicObject>`). Just several examples of such resources:
 + `discovery.k8s.io`: `EndpointSlice` is served on `endpointslices`, but inflector guesses `endpointsliceice`.
 + `metrics.k8s.io`: `NodeMetrics` is served on `nodes`, and `PodMetrics` is served on `pods`. Impossible to guess.

It seems that in typed case we can't get rid of inflector until `k8s-openapi` provides us with this information, but at least dynamic API should work without guessing URLs.

**Comment by MikailBag** [comment]
My proposal:
- Add new `resource_name` (or `endpoint`, I'm not good at naming) method to the `Meta` trait.
- Add a `name` field to `GVK`.
- `impl Meta for DynamicObject` is changed to return this `name`.
- `impl Meta for K where K: k8s_openapi::Resource` still uses `inflector`
- When at some moment k8s-openapi provides resource name, we just change that method to use this provided information instead of the calls to inflector.

**Comment by clux** [comment]
Yeah, we know this is bad. It's #284. Was hoping we'd get a fix in k8s-openapi, but no one has jumped on the issue there yet.

I think your proposal is reasonable. Now that `Meta` is unchained from `k8s-openapi` we can define what we want, and it seems a good place to start by fixing it there, and having the other one fallback to inflector for now.

We could potentially do one better by tackling cluster/namespaced scoping as part of the trait (see #199) as well (although one for a separate PR i think).

**Comment by clux** [comment]
As for naming; `plural` is probably what we want. It's what's used in `kube-derive`.

**Comment by kazk** [comment]
https://github.com/whatisinternet/Inflector/pull/73 fixes the `iceice`, but Inflector is no longer maintained. It's also a large dependency, and we don't need most of its features.

Do we have any irregular plurals to handle? I feel like we can use a much simpler function to handle basic pluralization instead.
