### ISSUE TITLE
Remove Inflector

### ISSUE THREAD

**Issue by kazk** [clux/kube-rs#470]
[Inflector](https://github.com/whatisinternet/Inflector) is no longer maintained. It's a large dependency, and we don't use most of its features (just `to_plural`). We should be able to replace it with a much simpler function by not trying to handle the irregulars. Inflector is buggy anyway (see https://github.com/clux/kube-rs/issues/467).

Here's a Rust port of a popular JavaScript package [plur](https://www.npmjs.com/package/plur) minus the irregular and case matching.
```rust
fn to_plural(word: &str) -> String {
    // Words ending in s, x, z, ch, sh will be pluralized with -es (eg. foxes).
    if word.ends_with('s')
        || word.ends_with('x')
        || word.ends_with('z')
        || word.ends_with("ch")
        || word.ends_with("sh")
    {
        return format!("{}es", word);
    }

    // Words ending in y that are preceded by a consonant will be pluralized by
    // replacing y with -ies (eg. puppies).
    if word.ends_with('y') {
        if let Some(c) = word.chars().nth(word.len() - 2) {
            if !matches!(c, 'a' | 'e' | 'i' | 'o' | 'u') {
                // Remove 'y' and add `ies`
                let mut chars = word.chars();
                chars.next_back();
                return format!("{}ies", chars.as_str());
            }
        }
    }

    // All other words will have "s" added to the end (eg. days).
    format!("{}s", word)
}
```

One concern is that this is not idempotent. (e.g., `Endpoints`. See https://github.com/clux/kube-rs/issues/284#issuecomment-671501175). We can special-case the native failures, and custom resource can specify irregular.

---

`is_pascal_case` is also used:
https://github.com/clux/kube-rs/blob/813da82a5924ca54829689eae9b88e2cef465494/kube/src/api/dynamic.rs#L171-L176

but I believe it should be removed. `kube-derive` side was removed https://github.com/clux/kube-rs/pull/321/commits/7187db7852de360f42ac690c4fb2451a2297a530

**Comment by clux** [comment]
I think a small helper to deal with this from a kube POV for now makes sense.
It lets us handle the special cases, and it'll give us a less heavy dependency, that's also probably better with its memory management: https://github.com/clux/kube-rs/issues/14#issuecomment-660053712
