### ISSUE TITLE
define a CustomResourceExt in kube for kube-derive

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#497]
For methods like `::crd` and `::api_resource` (see #495). Came up on discord last week, and it'll be useful to keep some guarantee on the generated code.

- [x] define trait in `kube_core/src/crd.rs` - probably fine to only target apiextensions v1
- [x] `impl CustomResourceExt` in `kube-derive`
- [x] figure out a migration strategy for v1beta1 users

cc @lfrancke.

**Comment by lfrancke** [comment]
Sorry for the late reply.
Yes, I think it'd be useful to have those in a trait.

I only have a single use-case in mind but I'm sure there are more.
If `::crd` were behind a trait I could create a simple method to write a CRD YAML to a file, to stdout or even to create it in Kubernetes for any resource. Now it needs custom code for every CRD.
