### ISSUE TITLE
"admission" feature not available?

### ISSUE THREAD

**Issue by kelko** [clux/kube-rs#513]
I'm trying to make an Admission controller like described in [the example](https://github.com/clux/kube-rs/blob/master/examples/admission_controller.rs).
With "simple" kube dependency I get the error, that `kube::api::admission` does not exist. Checked the `Cargo.toml` of the example directory and added the [`features = ["admission"]`](https://github.com/clux/kube-rs/blob/master/examples/Cargo.toml#L24) also to my Cargo.toml:
```toml
# ...
kube = { version = "0.52.0", features = ["admission"] }
kube-runtime = "0.52.0"
kube-derive = "0.52.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_18"] }
# ..
```

But now `cargo build` complains:
```
error: failed to select a version for `kube`.
    ... required by package `lsoperator v0.1.0 (SOMEFOLDER)`
versions that meet the requirements `=0.52.0` are: 0.52.0

the package `lsoperator` depends on `kube`, with features: `admission` but `kube` does not have these features.


failed to select a version for `kube` which could resolve this conflict
```

Installed versions (on a win 10):
```
> cargo --version
cargo 1.52.0 (69767412a 2021-04-21)

> rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

I'm still rather new to rust, maybe I just missed something. Then a pointer in the right direction would be very much appreciated.

**Comment by clux** [comment]
Ah, sorry. I have kept the feature in `master` for a while before releasing it. I am planning on releasing it this weekend, but if you want to use it in the mean time you have to use a cargo git dependency.
