### ISSUE TITLE
add DeleteParams for delete_collection

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#53]
We currently use ListParams but this is technically a bit wrong. See https://github.com/Arnavion/k8s-openapi/issues/46

**Comment by ericmcbride** [comment]
I can tackle this if still needed

**Comment by clux** [comment]
Yes please. If you can figure out what's actually inconsistent. It's been a while since I reported this :smile: 

We currently have `ListParams` in the signature for `delete_collection`, but should probably have some sort of `DeleteParams` instead. Possibly with the preconditions that Arnavion talks about https://arnavion.github.io/k8s-openapi/v0.7.x/k8s_openapi/struct.DeleteOptional.html#structfield.preconditions

**Comment by clux** [comment]
Fixed in 0.40.0.
