### ISSUE TITLE
Connection reset, using in-cluster authentication with the Client

### ISSUE THREAD

**Issue by jlpettersson** [clux/kube-rs#567]
A tried some basic code that connects to API Server:

```
let client_res = Client::try_default().await?;
client.apiserver_version().await?;
```

I run it in a Pod, so it is expected to detect and use "in-cluster" authentication.

The error I get on the request is:

```
HyperError(hyper::Error(Body, hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))
```

I am not sure there is good enough error information to understand **what** caused this error. Is there any logging to enable for this? Any other debug suggestion?

It might be that the ServiceAccount does not have enough permissions for the operation, but then I would expect an error message about that.

**Comment by clux** [comment]
Hm, that is strange. The normal error for access is an `ErrorResponse`:

```rust
Api(ErrorResponse { status: "Failure", message: "foos.clux.dev is forbidden: User \"system:serviceaccount:default:default\" cannot list resource \"foos\" in API group \"clux.dev\" at the cluster scope", reason: "Forbidden", code: 403 })'
```

so it should not be related to that (at least at this stage).

You could try to increase the logging level of kube by enabling trace logging:

```rust
std::env::set_var("RUST_LOG", "info,kube=trace");
```

**Comment by jlpettersson** [comment]
I tried to set the `RUST_LOG` variable, but I get no logging from the library.

I tried to add some `println!()` and from `config.auth_info` I can see:

```
token: Some(...), token_file: None, client_certificate: None, client_certificate_data: None, client_key: None, client_key_data: None
```
this is printed right before `let stack = ServiceBuilder::new()...`

So it looks like it did not load the client certificate from the service account token? Then maybe the connection is terminated immediately, perhaps.

**Comment by clux** [comment]
The `token` there is a `Some` so that means the token was loaded from the `SERVICE_TOKENFILE` (which is needed for it to not throw an `InvalidInClusterToken` error immediately). So I don't think it is that.

Some other info would be helpul: What's your environment? Does `Config::from_cluster_env()?` work, rather than `infer`? What's your `ServiceBuilder` building? Are you including all the standard layers? If you are building your own stack then you are bypassing our tracing.

**Comment by jlpettersson** [comment]
>Does Config::from_cluster_env()? work, rather than infer?

It looks like I use `infer` now, and `from_cluster_env()` from there returns "success" and I can see that `root_cert` contains data.

I use the client as a crate, the only modification I have done is adding `println!()` in a few places to try to understand the problem. I run the app on an AWS EKS cluster.

**Comment by clux** [comment]
Oh, right, sorry. I thought you were doing something advanced with the ServiceBuilder for a second.

Do you have a library to pick up on the tracing? Like tracing::fmt. The pod_api example has something for that.

**Comment by jlpettersson** [comment]
Thanks, got tracing logs now.

```
Jun 24 23:15:28.320 DEBUG HTTP{http.method=GET http.url=https://172.20.0.1:443/version otel.name="HTTP" otel.kind="client"}: kube::client: requesting
```
is the only log I get before the error
```
 HyperError(hyper::Error(Body, hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))
```
I can't tell what it is, but I suspect there is something with the TLS certificate authentication.

**Comment by kazk** [comment]
Are you using rustls?

**Comment by jlpettersson** [comment]
>Are you using rustls?

I used the default configuration. But this was a good suggestion of alternative to test.

But unfortunately I cannot build with `rustls-tls` as I cross-compile from MacOS.

```
error: failed to run custom build command for `ring v0.16.20`
```

```
.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesni-x86_64-elf.S"
  /Users/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesni-x86_64-elf.S:13:1: error: unknown directive
  .hidden GFp_ia32cap_P
  ^
```

**Comment by jlpettersson** [comment]
>Can you show the yaml you use to deploy the pod?

I think the Yaml should be ok, since I get a token from `config.auth_info` that is printed as `token: Some(...)` and the `...` is a JWT token. When I decode the token (after it is logged from kube-rs crate), it has the content below:

```
{
  "alg": "RS256",
  "kid": "PE2K31C8-aC0BFYCa_W9Gen4xo7lWZ16QaxvEgr8kaY"
}.{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "default",
  "kubernetes.io/serviceaccount/secret.name": "myapp-token-qhgr9",
  "kubernetes.io/serviceaccount/service-account.name": "myapp",
  "kubernetes.io/serviceaccount/service-account.uid": "aafa7ce7-861d-4ab2-9c0a-21522bc1f4b8",
  "sub": "system:serviceaccount:default:myapp"
}
```

I suspect the problem is with the TLS authentication, I guess this part involves some C-dependencies and maybe OpenSSL? Note that I cross-compile from MacOS to linux to be able to run on x86 docker containers. But I would hope that problems with those would generate compilation errors, similar to how my builds fails when building with `rustls-tls`.

In my Dockerfile, I use `ubuntu` as base image without other packages. But I might need to do some tricks to get TLS/SSL working.

**Comment by clux** [comment]
yeah, it still feels weird for me that it's auth, but sure maybe. at least you've got the token as you say.

You could try to deploy [version-rs](https://github.com/clux/version-rs) to see if it survives in the cluster, because that's a standard build-deploy setup that's used a lot of places. It uses latest kube-rs, and is [super quick to install](https://github.com/clux/version-rs/blob/master/deployment.yaml).

**Comment by jlpettersson** [comment]
>You could try to deploy version-rs to see if it survives in the cluster.

Yes, that one worked. I skipped the `sudo`-commands in the `Makefile` and built and deployed it without all the Yaml. Then I get a proper error from the API Server (e.g. this confirms that the connections to API Server works).

```
Jun 25 17:58:53.540 DEBUG kube::client: Unsuccessful: ErrorResponse { status: "Failure", message: "deployments.apps is forbidden: User \"system:serviceaccount:default:default\" cannot list resource \"deployments\" in API group \"apps\" in the namespace \"default\"", reason: "Forbidden", code: 403 }
```

So the main difference here is how the application is _built_. In the Makefile this binary is built from a Docker linux container:

```
        docker run --rm \
                -v $$PWD:/volume \
                -v cargo-cache:/root/.cargo/registry \
                -t clux/muslrust:stable cargo build --release
```

So I probably need to do it this way for my app as well, since `kube-rs` contains external C-dependencies. But on a Mac this goes slow since Docker is run on some form of VM.

Thanks for finding out of this. I wish there was a pure Rust TLS crate, not the first time I struggle with TLS when working with Rust :)

**Comment by kazk** [comment]
@jlpettersson Can you post how you were building?

> I wish there was a pure Rust TLS crate, not the first time I struggle with TLS when working with Rust :)

Yeah, we support rustls, but it still has a few limitations and cannot be used as a default.

**Comment by jlpettersson** [comment]
>Can you post how you were building?

From MacOS I cross-compile to Linux using:

```
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc cargo build --release --target=x86_64-unknown-linux-gnu
```
I use the same command both on MacOS arm64 and MacOS x86_64.

Before that, I install cross-compiler using:
```
rustup target add x86_64-unknown-linux-gnu

# Install a pre-built cross compiler
brew tap SergioBenitez/osxct
brew install x86_64-unknown-linux-gnu
```

**Comment by kazk** [comment]
Thanks, I've never cross compiled from macOS. Looking at `openssl` crate docs, you probably need to help it find the correct one with `X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR`.

Adding `openssl` with `vendored` feature to your `dependencies` to use `openssl-src` should work as well.

To make this (and Windows build) easier, we should probably add `native-tls-vendored` feature to `kube`.

> But `rustls` is not pure Rust, it is built upon `ring` that use C-dependencies, and therefore also is difficult for cross-compilation.

You're right, I forgot. https://github.com/briansmith/ring/blob/main/BUILDING.md#cross-compiling

**Comment by jamessewell** [comment]
After reading this I'm still not sure of how to fix this issue? I'm using nixos to build the container and it doesn't work - but other containers which need openssl work.

**Comment by jamessewell** [comment]
Ah. It's because the compiled object doesn't link to openssl, so it isn't pulled into the container.
