### ISSUE TITLE
Optional rustls support

### ISSUE THREAD

**Issue by jnicholls** [clux/kube-rs#66]
Some Rust users in the community are not interested in having OpenSSL as a dependency. Especially just for the support of loading certificate/key data from kubeconfig files. `reqwest` already supports `rustls` as an optional feature instead of using `native-tls`. You would simply need to switch the cert/key loading to only use reqwest Certificate/Identity APIs, and potentially [rustls::internal::pemfile](https://docs.rs/rustls/0.16.0/rustls/internal/pemfile/index.html) if necessary, rather than the openssl crate.

**Comment by clux** [comment]
Yeah, I would be very happy to support `rustls` as a feature (even having it as the default feature if it works well). Reqwest dependency is easy to switch out. My time is somewhat limited here, but would gladly take a PR for rustls support in the `config` module.

**Comment by clux** [comment]
@jnicholls I've tried following your plan in #114 using some of @ctron 's linked commit (ty). Unfortunately, have not been able to make it communicate with a cluster yet (just getting 403s back). My pem input + cert bundles all seem sensible afaikt, but have very little knowledge in this area. Any help to make this work would be appreciated.

**Comment by jnicholls** [comment]
@clux Thanks for jumping into this! You are amazing for creating and supporting this great library and just wanted to start with a big thank you.

This afternoon I will find some time to jump in here and see if I can lend a hand!

**Comment by clux** [comment]
Appreciate that! Just a heads up that the rustls issue is actually more or less resolved! Just need to tidy it up a bit for a release and port the oauth module.

Any more of the help that you've already jump on or want to jump on is still very much appreciated though!

**Comment by clux** [comment]
Initial support in master. Will release a version with it soon. But it's probably not usable for gke yet: see #120

**Comment by clux** [comment]
Released in 0.25.0 along with a great pr to help #120
