### ISSUE TITLE
Export Config API Structs from Crate

### ISSUE THREAD

**Issue by lawliet89** [clux/kube-rs#67]
Currently API types defined in [`config/apis.rs`](https://github.com/clux/kube-rs/blob/master/src/config/apis.rs) are not exported from the crate. Would like to see them exported.

I am currently writing a utility to manage some `kubeconfig` files. Instead of redefining the types myself, would be great if I can simply use the types exported by this library.

**Comment by clux** [comment]
Just the types? That can be done.

The methods on them are a bit ad-hoc at the moment and probably subject to change on the next refactor.

**Comment by clux** [comment]
How's this?

**Comment by lawliet89** [comment]
Thanks!

**Comment by ctron** [comment]
I just ran into this issue … actually it would be great to have the method for loading (`KubeConfigLoader::load`) public as well
