### ISSUE TITLE
Retrieve the default namespace when running in cluster

### ISSUE THREAD

**Issue by alecmocatta** [clux/kube-rs#69]
It's [documented](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod) to be in `/var/run/secrets/kubernetes.io/serviceaccount/namespace`.

Perhaps this could be surfaced somehow?

**Comment by clux** [comment]
Yeah, that should be pretty easy to implement. Unfortunately, my internet has disappeared. So marking as help wanted for now until it's restored.
