### ISSUE TITLE
tag version of source code

### ISSUE THREAD

**Issue by davidB** [clux/kube-rs#71]
Can you git tag your next version ? (for my own crates I use cargo-publish to tag + bump + push + publish to crates.io)

**Comment by clux** [comment]
Oh, I didn't know `cargo publish` could do that. Do you have a one-liner or an alias that's good?

**Comment by davidB** [comment]
Correction: not "cargo publish", but the [cargo-release](https://crates.io/crates/cargo-release) cli (Sorry)
In fact I drive `publish` with `cargo-make` (to be able to have a protable ci,....), that call `cargo release`, and I named the task publish (<= my confusion).

`cargo release minor`

**Comment by clux** [comment]
Oh, that's nicer. Thanks! I'll try to use that in the next minor!

**Comment by clux** [comment]
Tagged 0.17.0
