### ISSUE TITLE
Switch to async-compatible locks in informer and reflector

### ISSUE THREAD

**Issue by kitfre** [clux/kube-rs#94]
Currently there are some `RwLock`s used in informer and reflector that are locked during an async path. This will lock the entire event loop as `RwLock` is a synchronous construct. Instead using something async compatible like `futures::lock::Mutex`. Currently there doesn't seem to be any implementations of an async `RwLock`, but there looks to be some progress towards that end in tokio - tokio-rs/tokio#1665.

This is my bad 🤦‍♂ I should have noticed and included this in #92

**Comment by clux** [comment]
Fixed in #94.
Thanks again :slightly_smiling_face:
